// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hierarchy/grpcapi.proto

package grpcapi

import (
	fmt "fmt"
	common "github.com/SKF/proto/common"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_NUMERIC       ValueType = 0
	ValueType_SINGLE_CHOICE ValueType = 1
	ValueType_MULTI_CHOICE  ValueType = 2
)

var ValueType_name = map[int32]string{
	0: "NUMERIC",
	1: "SINGLE_CHOICE",
	2: "MULTI_CHOICE",
}

var ValueType_value = map[string]int32{
	"NUMERIC":       0,
	"SINGLE_CHOICE": 1,
	"MULTI_CHOICE":  2,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}

func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{0}
}

type LubricantUnit int32

const (
	LubricantUnit_GRAM  LubricantUnit = 0
	LubricantUnit_OUNCE LubricantUnit = 1
	LubricantUnit_CM3   LubricantUnit = 2
)

var LubricantUnit_name = map[int32]string{
	0: "GRAM",
	1: "OUNCE",
	2: "CM3",
}

var LubricantUnit_value = map[string]int32{
	"GRAM":  0,
	"OUNCE": 1,
	"CM3":   2,
}

func (x LubricantUnit) String() string {
	return proto.EnumName(LubricantUnit_name, int32(x))
}

func (LubricantUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{1}
}

type MeasurementPoint struct {
	Angular              string   `protobuf:"bytes,1,opt,name=angular,proto3" json:"angular,omitempty"`
	Bearing              int32    `protobuf:"varint,3,opt,name=bearing,proto3" json:"bearing,omitempty"`
	MeasurementType      string   `protobuf:"bytes,4,opt,name=measurementType,proto3" json:"measurementType,omitempty"`
	Shaft                string   `protobuf:"bytes,5,opt,name=shaft,proto3" json:"shaft,omitempty"`
	ShaftSide            string   `protobuf:"bytes,6,opt,name=shaftSide,proto3" json:"shaftSide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeasurementPoint) Reset()         { *m = MeasurementPoint{} }
func (m *MeasurementPoint) String() string { return proto.CompactTextString(m) }
func (*MeasurementPoint) ProtoMessage()    {}
func (*MeasurementPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{0}
}

func (m *MeasurementPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementPoint.Unmarshal(m, b)
}
func (m *MeasurementPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementPoint.Marshal(b, m, deterministic)
}
func (m *MeasurementPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementPoint.Merge(m, src)
}
func (m *MeasurementPoint) XXX_Size() int {
	return xxx_messageInfo_MeasurementPoint.Size(m)
}
func (m *MeasurementPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementPoint proto.InternalMessageInfo

func (m *MeasurementPoint) GetAngular() string {
	if m != nil {
		return m.Angular
	}
	return ""
}

func (m *MeasurementPoint) GetBearing() int32 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *MeasurementPoint) GetMeasurementType() string {
	if m != nil {
		return m.MeasurementType
	}
	return ""
}

func (m *MeasurementPoint) GetShaft() string {
	if m != nil {
		return m.Shaft
	}
	return ""
}

func (m *MeasurementPoint) GetShaftSide() string {
	if m != nil {
		return m.ShaftSide
	}
	return ""
}

type InspectionPoint struct {
	OBSOLETEValueType    string    `protobuf:"bytes,1,opt,name=OBSOLETE_valueType,json=OBSOLETEValueType,proto3" json:"OBSOLETE_valueType,omitempty"`
	ValueType            ValueType `protobuf:"varint,4,opt,name=valueType,proto3,enum=grpcapi.ValueType" json:"valueType,omitempty"`
	NumericUnit          string    `protobuf:"bytes,2,opt,name=numericUnit,proto3" json:"numericUnit,omitempty"`
	Answers              []string  `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InspectionPoint) Reset()         { *m = InspectionPoint{} }
func (m *InspectionPoint) String() string { return proto.CompactTextString(m) }
func (*InspectionPoint) ProtoMessage()    {}
func (*InspectionPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{1}
}

func (m *InspectionPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectionPoint.Unmarshal(m, b)
}
func (m *InspectionPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectionPoint.Marshal(b, m, deterministic)
}
func (m *InspectionPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectionPoint.Merge(m, src)
}
func (m *InspectionPoint) XXX_Size() int {
	return xxx_messageInfo_InspectionPoint.Size(m)
}
func (m *InspectionPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectionPoint.DiscardUnknown(m)
}

var xxx_messageInfo_InspectionPoint proto.InternalMessageInfo

func (m *InspectionPoint) GetOBSOLETEValueType() string {
	if m != nil {
		return m.OBSOLETEValueType
	}
	return ""
}

func (m *InspectionPoint) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_NUMERIC
}

func (m *InspectionPoint) GetNumericUnit() string {
	if m != nil {
		return m.NumericUnit
	}
	return ""
}

func (m *InspectionPoint) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

type LubricationPoint struct {
	Bearing              int32         `protobuf:"varint,1,opt,name=bearing,proto3" json:"bearing,omitempty"`
	Lubricant            string        `protobuf:"bytes,2,opt,name=lubricant,proto3" json:"lubricant,omitempty"`
	Volume               int32         `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Unit                 LubricantUnit `protobuf:"varint,4,opt,name=unit,proto3,enum=grpcapi.LubricantUnit" json:"unit,omitempty"`
	Interval             int32         `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LubricationPoint) Reset()         { *m = LubricationPoint{} }
func (m *LubricationPoint) String() string { return proto.CompactTextString(m) }
func (*LubricationPoint) ProtoMessage()    {}
func (*LubricationPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{2}
}

func (m *LubricationPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LubricationPoint.Unmarshal(m, b)
}
func (m *LubricationPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LubricationPoint.Marshal(b, m, deterministic)
}
func (m *LubricationPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LubricationPoint.Merge(m, src)
}
func (m *LubricationPoint) XXX_Size() int {
	return xxx_messageInfo_LubricationPoint.Size(m)
}
func (m *LubricationPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_LubricationPoint.DiscardUnknown(m)
}

var xxx_messageInfo_LubricationPoint proto.InternalMessageInfo

func (m *LubricationPoint) GetBearing() int32 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *LubricationPoint) GetLubricant() string {
	if m != nil {
		return m.Lubricant
	}
	return ""
}

func (m *LubricationPoint) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *LubricationPoint) GetUnit() LubricantUnit {
	if m != nil {
		return m.Unit
	}
	return LubricantUnit_GRAM
}

func (m *LubricationPoint) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type AssetNode struct {
	Criticality          string   `protobuf:"bytes,1,opt,name=criticality,proto3" json:"criticality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetNode) Reset()         { *m = AssetNode{} }
func (m *AssetNode) String() string { return proto.CompactTextString(m) }
func (*AssetNode) ProtoMessage()    {}
func (*AssetNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{3}
}

func (m *AssetNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetNode.Unmarshal(m, b)
}
func (m *AssetNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetNode.Marshal(b, m, deterministic)
}
func (m *AssetNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetNode.Merge(m, src)
}
func (m *AssetNode) XXX_Size() int {
	return xxx_messageInfo_AssetNode.Size(m)
}
func (m *AssetNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetNode.DiscardUnknown(m)
}

var xxx_messageInfo_AssetNode proto.InternalMessageInfo

func (m *AssetNode) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

type Node struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label                string                  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description          string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string                  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Criticality          string                  `protobuf:"bytes,5,opt,name=criticality,proto3" json:"criticality,omitempty"`
	SubType              string                  `protobuf:"bytes,6,opt,name=subType,proto3" json:"subType,omitempty"`
	Origin               *common.Origin          `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	AssetNode            *AssetNode              `protobuf:"bytes,8,opt,name=assetNode,proto3" json:"assetNode,omitempty"`
	MeasurementPoint     *MeasurementPoint       `protobuf:"bytes,9,opt,name=measurementPoint,proto3" json:"measurementPoint,omitempty"`
	InspectionPoint      *InspectionPoint        `protobuf:"bytes,10,opt,name=inspectionPoint,proto3" json:"inspectionPoint,omitempty"`
	LubricationPoint     *LubricationPoint       `protobuf:"bytes,14,opt,name=lubricationPoint,proto3" json:"lubricationPoint,omitempty"`
	ChildOrderNumber     int64                   `protobuf:"varint,11,opt,name=childOrderNumber,proto3" json:"childOrderNumber,omitempty"` // Deprecated: Do not use.
	Position             *common.PrimitiveInt64  `protobuf:"bytes,12,opt,name=position,proto3" json:"position,omitempty"`
	Tags                 *common.PrimitiveString `protobuf:"bytes,13,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{4}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Node) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

func (m *Node) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Node) GetOrigin() *common.Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Node) GetAssetNode() *AssetNode {
	if m != nil {
		return m.AssetNode
	}
	return nil
}

func (m *Node) GetMeasurementPoint() *MeasurementPoint {
	if m != nil {
		return m.MeasurementPoint
	}
	return nil
}

func (m *Node) GetInspectionPoint() *InspectionPoint {
	if m != nil {
		return m.InspectionPoint
	}
	return nil
}

func (m *Node) GetLubricationPoint() *LubricationPoint {
	if m != nil {
		return m.LubricationPoint
	}
	return nil
}

// Deprecated: Do not use.
func (m *Node) GetChildOrderNumber() int64 {
	if m != nil {
		return m.ChildOrderNumber
	}
	return 0
}

func (m *Node) GetPosition() *common.PrimitiveInt64 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Node) GetTags() *common.PrimitiveString {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{5}
}

func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetEventsInput struct {
	Since                int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	Limit                *common.PrimitiveInt32 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetEventsInput) Reset()         { *m = GetEventsInput{} }
func (m *GetEventsInput) String() string { return proto.CompactTextString(m) }
func (*GetEventsInput) ProtoMessage()    {}
func (*GetEventsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{6}
}

func (m *GetEventsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsInput.Unmarshal(m, b)
}
func (m *GetEventsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsInput.Marshal(b, m, deterministic)
}
func (m *GetEventsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsInput.Merge(m, src)
}
func (m *GetEventsInput) XXX_Size() int {
	return xxx_messageInfo_GetEventsInput.Size(m)
}
func (m *GetEventsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsInput proto.InternalMessageInfo

func (m *GetEventsInput) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetEventsInput) GetLimit() *common.PrimitiveInt32 {
	if m != nil {
		return m.Limit
	}
	return nil
}

type GetEventsOutput struct {
	Events               []byte   `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsOutput) Reset()         { *m = GetEventsOutput{} }
func (m *GetEventsOutput) String() string { return proto.CompactTextString(m) }
func (*GetEventsOutput) ProtoMessage()    {}
func (*GetEventsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{7}
}

func (m *GetEventsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsOutput.Unmarshal(m, b)
}
func (m *GetEventsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsOutput.Marshal(b, m, deterministic)
}
func (m *GetEventsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsOutput.Merge(m, src)
}
func (m *GetEventsOutput) XXX_Size() int {
	return xxx_messageInfo_GetEventsOutput.Size(m)
}
func (m *GetEventsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsOutput proto.InternalMessageInfo

func (m *GetEventsOutput) GetEvents() []byte {
	if m != nil {
		return m.Events
	}
	return nil
}

type SaveNodeInput struct {
	UserId               string         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Node                 *Node          `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	ParentId             string         `protobuf:"bytes,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ParentOrigin         *common.Origin `protobuf:"bytes,4,opt,name=parentOrigin,proto3" json:"parentOrigin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveNodeInput) Reset()         { *m = SaveNodeInput{} }
func (m *SaveNodeInput) String() string { return proto.CompactTextString(m) }
func (*SaveNodeInput) ProtoMessage()    {}
func (*SaveNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{8}
}

func (m *SaveNodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveNodeInput.Unmarshal(m, b)
}
func (m *SaveNodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveNodeInput.Marshal(b, m, deterministic)
}
func (m *SaveNodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveNodeInput.Merge(m, src)
}
func (m *SaveNodeInput) XXX_Size() int {
	return xxx_messageInfo_SaveNodeInput.Size(m)
}
func (m *SaveNodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveNodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_SaveNodeInput proto.InternalMessageInfo

func (m *SaveNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SaveNodeInput) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SaveNodeInput) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SaveNodeInput) GetParentOrigin() *common.Origin {
	if m != nil {
		return m.ParentOrigin
	}
	return nil
}

type DeleteNodeInput struct {
	UserId               string         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NodeId               string         `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Origin               *common.Origin `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteNodeInput) Reset()         { *m = DeleteNodeInput{} }
func (m *DeleteNodeInput) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeInput) ProtoMessage()    {}
func (*DeleteNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{9}
}

func (m *DeleteNodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeInput.Unmarshal(m, b)
}
func (m *DeleteNodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeInput.Marshal(b, m, deterministic)
}
func (m *DeleteNodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeInput.Merge(m, src)
}
func (m *DeleteNodeInput) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeInput.Size(m)
}
func (m *DeleteNodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeInput proto.InternalMessageInfo

func (m *DeleteNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteNodeInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DeleteNodeInput) GetOrigin() *common.Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type GetAncestorsInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAncestorsInput) Reset()         { *m = GetAncestorsInput{} }
func (m *GetAncestorsInput) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsInput) ProtoMessage()    {}
func (*GetAncestorsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{10}
}

func (m *GetAncestorsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsInput.Unmarshal(m, b)
}
func (m *GetAncestorsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsInput.Marshal(b, m, deterministic)
}
func (m *GetAncestorsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsInput.Merge(m, src)
}
func (m *GetAncestorsInput) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsInput.Size(m)
}
func (m *GetAncestorsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsInput proto.InternalMessageInfo

func (m *GetAncestorsInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetAncestorsOutput struct {
	Nodes                []*AncestorNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAncestorsOutput) Reset()         { *m = GetAncestorsOutput{} }
func (m *GetAncestorsOutput) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsOutput) ProtoMessage()    {}
func (*GetAncestorsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{11}
}

func (m *GetAncestorsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsOutput.Unmarshal(m, b)
}
func (m *GetAncestorsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsOutput.Marshal(b, m, deterministic)
}
func (m *GetAncestorsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsOutput.Merge(m, src)
}
func (m *GetAncestorsOutput) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsOutput.Size(m)
}
func (m *GetAncestorsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsOutput proto.InternalMessageInfo

func (m *GetAncestorsOutput) GetNodes() []*AncestorNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AncestorNode struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               *common.Origin `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Label                string         `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description          string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string         `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	SubType              string         `protobuf:"bytes,6,opt,name=subType,proto3" json:"subType,omitempty"`
	ParentId             string         `protobuf:"bytes,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AncestorNode) Reset()         { *m = AncestorNode{} }
func (m *AncestorNode) String() string { return proto.CompactTextString(m) }
func (*AncestorNode) ProtoMessage()    {}
func (*AncestorNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d2394d36d1a269, []int{12}
}

func (m *AncestorNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AncestorNode.Unmarshal(m, b)
}
func (m *AncestorNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AncestorNode.Marshal(b, m, deterministic)
}
func (m *AncestorNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AncestorNode.Merge(m, src)
}
func (m *AncestorNode) XXX_Size() int {
	return xxx_messageInfo_AncestorNode.Size(m)
}
func (m *AncestorNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AncestorNode.DiscardUnknown(m)
}

var xxx_messageInfo_AncestorNode proto.InternalMessageInfo

func (m *AncestorNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AncestorNode) GetOrigin() *common.Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *AncestorNode) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AncestorNode) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AncestorNode) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AncestorNode) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *AncestorNode) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpcapi.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("grpcapi.LubricantUnit", LubricantUnit_name, LubricantUnit_value)
	proto.RegisterType((*MeasurementPoint)(nil), "grpcapi.MeasurementPoint")
	proto.RegisterType((*InspectionPoint)(nil), "grpcapi.InspectionPoint")
	proto.RegisterType((*LubricationPoint)(nil), "grpcapi.LubricationPoint")
	proto.RegisterType((*AssetNode)(nil), "grpcapi.AssetNode")
	proto.RegisterType((*Node)(nil), "grpcapi.Node")
	proto.RegisterType((*Nodes)(nil), "grpcapi.Nodes")
	proto.RegisterType((*GetEventsInput)(nil), "grpcapi.GetEventsInput")
	proto.RegisterType((*GetEventsOutput)(nil), "grpcapi.GetEventsOutput")
	proto.RegisterType((*SaveNodeInput)(nil), "grpcapi.SaveNodeInput")
	proto.RegisterType((*DeleteNodeInput)(nil), "grpcapi.DeleteNodeInput")
	proto.RegisterType((*GetAncestorsInput)(nil), "grpcapi.GetAncestorsInput")
	proto.RegisterType((*GetAncestorsOutput)(nil), "grpcapi.GetAncestorsOutput")
	proto.RegisterType((*AncestorNode)(nil), "grpcapi.AncestorNode")
}

func init() { proto.RegisterFile("hierarchy/grpcapi.proto", fileDescriptor_17d2394d36d1a269) }

var fileDescriptor_17d2394d36d1a269 = []byte{
	// 1092 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xf3, 0xef, 0xd3, 0x24, 0x4d, 0x0f, 0x90, 0x7a, 0x43, 0x2f, 0x82, 0x91, 0x50, 0xe8,
	0xb6, 0x59, 0x94, 0xc2, 0x4a, 0x20, 0x2d, 0xa2, 0xed, 0x86, 0xac, 0x45, 0xdb, 0x54, 0x4e, 0xbb,
	0xb7, 0x95, 0xe3, 0x0c, 0xe9, 0x48, 0x8e, 0x1d, 0x8d, 0xc7, 0x41, 0x7d, 0x15, 0xae, 0xb9, 0xda,
	0x0b, 0x9e, 0x83, 0x77, 0xe0, 0x01, 0x78, 0x0d, 0x34, 0xe3, 0xdf, 0x38, 0xa4, 0x62, 0xaf, 0xe2,
	0x33, 0xe7, 0x3b, 0xe3, 0xf3, 0xf3, 0x9d, 0xcf, 0x81, 0xc3, 0x47, 0x4a, 0x98, 0xc5, 0xec, 0xc7,
	0xa7, 0x57, 0x0b, 0xb6, 0xb2, 0xad, 0x15, 0x1d, 0xac, 0x98, 0xc7, 0x3d, 0xac, 0x45, 0x66, 0xf7,
	0x13, 0xdb, 0x5b, 0x2e, 0x3d, 0xf7, 0x55, 0xf8, 0x13, 0x7a, 0xf5, 0x3f, 0x14, 0x68, 0x5f, 0x13,
	0xcb, 0x0f, 0x18, 0x59, 0x12, 0x97, 0xdf, 0x7a, 0xd4, 0xe5, 0xa8, 0x41, 0xcd, 0x72, 0x17, 0x81,
	0x63, 0x31, 0x4d, 0xe9, 0x29, 0x7d, 0xd5, 0x8c, 0x4d, 0xe1, 0x99, 0x11, 0x8b, 0x51, 0x77, 0xa1,
	0x95, 0x7a, 0x4a, 0xbf, 0x62, 0xc6, 0x26, 0xf6, 0x61, 0x7f, 0x99, 0xde, 0x73, 0xf7, 0xb4, 0x22,
	0x5a, 0x59, 0xc6, 0xe6, 0x8f, 0xf1, 0x53, 0xa8, 0xf8, 0x8f, 0xd6, 0xaf, 0x5c, 0xab, 0x48, 0x7f,
	0x68, 0xe0, 0x11, 0xa8, 0xf2, 0x61, 0x4a, 0xe7, 0x44, 0xab, 0x4a, 0x4f, 0x7a, 0xa0, 0xff, 0xa9,
	0xc0, 0xbe, 0xe1, 0xfa, 0x2b, 0x62, 0x73, 0xea, 0xb9, 0x61, 0x96, 0xa7, 0x80, 0x93, 0x8b, 0xe9,
	0xe4, 0x6a, 0x74, 0x37, 0x7a, 0x58, 0x5b, 0x4e, 0x40, 0xe4, 0x4b, 0xc3, 0x84, 0x0f, 0x62, 0xcf,
	0xfb, 0xd8, 0x81, 0xdf, 0x80, 0x9a, 0xa2, 0x44, 0x6a, 0xad, 0x21, 0x0e, 0xe2, 0x56, 0x25, 0x30,
	0x33, 0x05, 0x61, 0x0f, 0xf6, 0xdc, 0x60, 0x49, 0x18, 0xb5, 0xef, 0x5d, 0xca, 0xb5, 0xa2, 0xbc,
	0x39, 0x7b, 0x14, 0x36, 0xca, 0xff, 0x8d, 0x30, 0x5f, 0x2b, 0xf5, 0x4a, 0x61, 0xa3, 0xa4, 0xa9,
	0x7f, 0x50, 0xa0, 0x7d, 0x15, 0xcc, 0x18, 0xb5, 0xad, 0x34, 0xe3, 0x4c, 0xf7, 0x94, 0xcd, 0xee,
	0x1d, 0x81, 0xea, 0x84, 0x68, 0x37, 0x7e, 0x51, 0x7a, 0x80, 0x1d, 0xa8, 0xae, 0x3d, 0x27, 0x58,
	0x92, 0xa8, 0xe9, 0x91, 0x85, 0xc7, 0x50, 0x0e, 0x44, 0x66, 0x61, 0x35, 0x9d, 0xa4, 0x9a, 0xab,
	0x38, 0x52, 0x24, 0x69, 0x4a, 0x0c, 0x76, 0xa1, 0x4e, 0x5d, 0x4e, 0xd8, 0xda, 0x72, 0x64, 0xe3,
	0x2b, 0x66, 0x62, 0xeb, 0xa7, 0xa0, 0x9e, 0xfb, 0x3e, 0xe1, 0x37, 0xde, 0x5c, 0x56, 0x6d, 0x33,
	0xca, 0xa9, 0x6d, 0x39, 0x94, 0x3f, 0x45, 0xfd, 0xcc, 0x1e, 0xe9, 0x7f, 0x97, 0xa1, 0x2c, 0xa1,
	0x2d, 0x28, 0xd2, 0x79, 0x84, 0x28, 0xd2, 0xb9, 0x98, 0xac, 0x63, 0xcd, 0x88, 0x13, 0x55, 0x10,
	0x1a, 0xe2, 0xc2, 0x39, 0xf1, 0x6d, 0x46, 0x57, 0xa2, 0x13, 0xb2, 0x04, 0xd5, 0xcc, 0x1e, 0x21,
	0x42, 0x99, 0xa7, 0x84, 0x91, 0xcf, 0xf9, 0x34, 0x2a, 0x5b, 0x69, 0x88, 0x6e, 0xfa, 0xc1, 0x4c,
	0x8e, 0x33, 0xe4, 0x4b, 0x6c, 0xe2, 0x57, 0x50, 0xf5, 0x18, 0x5d, 0x50, 0x57, 0xab, 0xf5, 0x94,
	0xfe, 0xde, 0xb0, 0x35, 0x88, 0x38, 0x3f, 0x91, 0xa7, 0x66, 0xe4, 0x15, 0x94, 0xb0, 0xe2, 0xba,
	0xb5, 0xba, 0x84, 0xa6, 0x94, 0x48, 0x3a, 0x62, 0xa6, 0x20, 0x1c, 0x41, 0x7b, 0x99, 0xdb, 0x16,
	0x4d, 0x95, 0x81, 0x2f, 0x92, 0xc0, 0xfc, 0x3a, 0x99, 0x5b, 0x21, 0x78, 0x01, 0xfb, 0x74, 0x93,
	0xcd, 0x1a, 0xc8, 0x5b, 0xb4, 0xe4, 0x96, 0x1c, 0xdb, 0xcd, 0x7c, 0x80, 0x48, 0xc5, 0xc9, 0x11,
	0x4c, 0x6b, 0xe5, 0x52, 0xc9, 0x33, 0xd0, 0xdc, 0x0a, 0xc1, 0x01, 0xb4, 0xed, 0x47, 0xea, 0xcc,
	0x27, 0x6c, 0x4e, 0xd8, 0x4d, 0xb0, 0x9c, 0x11, 0xa6, 0xed, 0xf5, 0x94, 0x7e, 0xe9, 0xa2, 0xa8,
	0x29, 0xe6, 0x96, 0x0f, 0x87, 0x50, 0x5f, 0x79, 0x3e, 0x95, 0xa3, 0x6c, 0xc8, 0xd7, 0x75, 0xe2,
	0xee, 0xde, 0x32, 0xba, 0xa4, 0x9c, 0xae, 0x89, 0xe1, 0xf2, 0xd7, 0xdf, 0x9a, 0x09, 0x0e, 0x5f,
	0x42, 0x99, 0x5b, 0x0b, 0x5f, 0x6b, 0x4a, 0xfc, 0xe1, 0x16, 0x7e, 0xca, 0xc5, 0x12, 0x98, 0x12,
	0xa4, 0x9f, 0x40, 0x45, 0xb4, 0xda, 0xc7, 0x2f, 0xa1, 0xe2, 0x8a, 0x07, 0x4d, 0xe9, 0x95, 0xfa,
	0x7b, 0xc3, 0x66, 0x52, 0x95, 0x1c, 0x4a, 0xe8, 0xd3, 0xef, 0xa0, 0x35, 0x26, 0x7c, 0xb4, 0x26,
	0x2e, 0xf7, 0x0d, 0x77, 0x15, 0x70, 0x29, 0x2f, 0xd4, 0xb5, 0x43, 0x25, 0x28, 0x99, 0xa1, 0x81,
	0x27, 0x50, 0x71, 0xc4, 0xdb, 0x24, 0x35, 0x77, 0xe4, 0x7c, 0x36, 0x34, 0x43, 0x90, 0xfe, 0x35,
	0xec, 0x27, 0xb7, 0x4e, 0x02, 0x2e, 0xae, 0xed, 0x40, 0x95, 0x48, 0x5b, 0xde, 0xdb, 0x30, 0x23,
	0x4b, 0xff, 0x5d, 0x81, 0xe6, 0xd4, 0x5a, 0x13, 0x91, 0x54, 0x98, 0x40, 0x07, 0xaa, 0x81, 0x4f,
	0x98, 0x11, 0x6f, 0x46, 0x64, 0xe1, 0x17, 0x50, 0x16, 0x39, 0xcb, 0x05, 0xd8, 0x2a, 0x47, 0xba,
	0xc4, 0x92, 0xae, 0x2c, 0x46, 0x5c, 0x6e, 0xcc, 0xa3, 0x1d, 0x4a, 0x6c, 0x1c, 0x42, 0x23, 0x7c,
	0x0e, 0x49, 0x2c, 0x97, 0x65, 0x9b, 0xda, 0x1b, 0x18, 0x9d, 0xc2, 0xfe, 0x5b, 0xe2, 0x10, 0xfe,
	0x3f, 0xb2, 0xeb, 0x40, 0x55, 0xa4, 0x90, 0xbc, 0x38, 0xb2, 0x32, 0xbb, 0x54, 0x7a, 0x6e, 0x97,
	0xf4, 0x13, 0x38, 0x18, 0x13, 0x7e, 0xee, 0xda, 0xc4, 0xe7, 0x1e, 0x8b, 0x66, 0x71, 0x08, 0x35,
	0x71, 0xcd, 0x43, 0xa2, 0x12, 0xd1, 0xad, 0xfa, 0x39, 0x60, 0x16, 0x1d, 0xf5, 0xf8, 0xe5, 0xe6,
	0xc4, 0x3f, 0x4b, 0x77, 0x31, 0x02, 0x66, 0x27, 0xff, 0x97, 0x02, 0x8d, 0xec, 0xf9, 0x96, 0x1a,
	0xa5, 0x99, 0x17, 0x9f, 0x55, 0x81, 0x44, 0xb5, 0x4a, 0xcf, 0xa8, 0x56, 0x79, 0xb7, 0x6a, 0x55,
	0x32, 0xaa, 0xb5, 0x5b, 0x93, 0xb2, 0xa3, 0xad, 0x6d, 0x8e, 0xf6, 0xf8, 0x0d, 0xa8, 0xe9, 0x77,
	0x6a, 0x0f, 0x6a, 0x37, 0xf7, 0xd7, 0x23, 0xd3, 0xb8, 0x6c, 0x17, 0xf0, 0x00, 0x9a, 0x53, 0xe3,
	0x66, 0x7c, 0x35, 0x7a, 0xb8, 0x7c, 0x37, 0x31, 0x2e, 0x47, 0x6d, 0x05, 0xdb, 0xd0, 0xb8, 0xbe,
	0xbf, 0xba, 0x33, 0xe2, 0x93, 0xe2, 0xf1, 0x29, 0x34, 0x37, 0x14, 0x1f, 0xeb, 0x50, 0x1e, 0x9b,
	0xe7, 0xd7, 0xed, 0x02, 0xaa, 0x50, 0x99, 0xdc, 0xdf, 0xc8, 0xb8, 0x1a, 0x94, 0x2e, 0xaf, 0xcf,
	0xda, 0xc5, 0xe1, 0x3f, 0x65, 0x50, 0xdf, 0xc5, 0x7f, 0x16, 0xf0, 0x0c, 0xea, 0x6f, 0x09, 0x59,
	0xdd, 0x8a, 0xaf, 0x50, 0x23, 0xee, 0xd0, 0x7b, 0x8f, 0xce, 0xbb, 0xbb, 0xf6, 0x54, 0x2f, 0xe0,
	0x19, 0xd4, 0xc6, 0x91, 0x22, 0xee, 0x42, 0x75, 0x37, 0x09, 0xae, 0x17, 0xf0, 0x3b, 0xa8, 0x47,
	0x41, 0xfe, 0xee, 0xa8, 0xd6, 0x46, 0x94, 0xaf, 0x17, 0xf0, 0x07, 0x68, 0x8e, 0x09, 0xbf, 0x14,
	0x3a, 0xf4, 0xd1, 0xb1, 0xdf, 0xcb, 0xd8, 0x5b, 0xd9, 0xe7, 0x8f, 0xcc, 0xd6, 0x80, 0x46, 0x96,
	0xa1, 0xd8, 0x4d, 0x00, 0x5b, 0x34, 0xef, 0x7e, 0xfe, 0x9f, 0xbe, 0x90, 0xd4, 0x7a, 0x01, 0x7f,
	0x94, 0xab, 0x21, 0x57, 0x70, 0x7e, 0xf1, 0x14, 0xb2, 0x0f, 0x73, 0x6c, 0x7c, 0xae, 0xdb, 0x6f,
	0xa0, 0x1e, 0x2b, 0x0c, 0xa6, 0x1f, 0xf9, 0x0d, 0xd1, 0x79, 0x2e, 0xfc, 0x35, 0x40, 0x2a, 0x02,
	0x98, 0x7e, 0x61, 0x72, 0xca, 0xd0, 0xdd, 0x98, 0xbe, 0x5e, 0xc0, 0x9f, 0x40, 0x4d, 0x44, 0x10,
	0x0f, 0xb3, 0x25, 0x66, 0xe4, 0xb6, 0xab, 0x6d, 0x3b, 0xe2, 0xc2, 0x2f, 0x8e, 0x3e, 0x14, 0x5f,
	0x4c, 0x7f, 0xf9, 0x79, 0x30, 0x72, 0x1d, 0xba, 0x78, 0xe4, 0x83, 0xf3, 0x5b, 0x63, 0x90, 0x30,
	0x6f, 0x56, 0x95, 0xff, 0x40, 0xcf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x10, 0x93, 0x8c, 0x9e,
	0xba, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HierarchyClient is the client API for Hierarchy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HierarchyClient interface {
	DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error)
	GetNode(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Node, error)
	GetNodes(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Nodes, error)
	GetChildNodes(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Nodes, error)
	GetParentNode(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Node, error)
	GetAncestors(ctx context.Context, in *GetAncestorsInput, opts ...grpc.CallOption) (*GetAncestorsOutput, error)
	GetNodeIdByOrigin(ctx context.Context, in *common.Origin, opts ...grpc.CallOption) (*common.PrimitiveString, error)
	SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*common.PrimitiveString, error)
	DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*common.Void, error)
	GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error)
}

type hierarchyClient struct {
	cc *grpc.ClientConn
}

func NewHierarchyClient(cc *grpc.ClientConn) HierarchyClient {
	return &hierarchyClient{cc}
}

func (c *hierarchyClient) DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error) {
	out := new(common.PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNode(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNodes(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetChildNodes(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetChildNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetParentNode(ctx context.Context, in *common.PrimitiveString, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetParentNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetAncestors(ctx context.Context, in *GetAncestorsInput, opts ...grpc.CallOption) (*GetAncestorsOutput, error) {
	out := new(GetAncestorsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetAncestors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNodeIdByOrigin(ctx context.Context, in *common.Origin, opts ...grpc.CallOption) (*common.PrimitiveString, error) {
	out := new(common.PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNodeIdByOrigin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*common.PrimitiveString, error) {
	out := new(common.PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/SaveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error) {
	out := new(GetEventsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HierarchyServer is the server API for Hierarchy service.
type HierarchyServer interface {
	DeepPing(context.Context, *common.Void) (*common.PrimitiveString, error)
	GetNode(context.Context, *common.PrimitiveString) (*Node, error)
	GetNodes(context.Context, *common.PrimitiveString) (*Nodes, error)
	GetChildNodes(context.Context, *common.PrimitiveString) (*Nodes, error)
	GetParentNode(context.Context, *common.PrimitiveString) (*Node, error)
	GetAncestors(context.Context, *GetAncestorsInput) (*GetAncestorsOutput, error)
	GetNodeIdByOrigin(context.Context, *common.Origin) (*common.PrimitiveString, error)
	SaveNode(context.Context, *SaveNodeInput) (*common.PrimitiveString, error)
	DeleteNode(context.Context, *DeleteNodeInput) (*common.Void, error)
	GetEvents(context.Context, *GetEventsInput) (*GetEventsOutput, error)
}

func RegisterHierarchyServer(s *grpc.Server, srv HierarchyServer) {
	s.RegisterService(&_Hierarchy_serviceDesc, srv)
}

func _Hierarchy_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeepPing(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNode(ctx, req.(*common.PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNodes(ctx, req.(*common.PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetChildNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetChildNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetChildNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetChildNodes(ctx, req.(*common.PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetParentNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetParentNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetParentNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetParentNode(ctx, req.(*common.PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetAncestors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetAncestors(ctx, req.(*GetAncestorsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNodeIdByOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Origin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNodeIdByOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNodeIdByOrigin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNodeIdByOrigin(ctx, req.(*common.Origin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_SaveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).SaveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/SaveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).SaveNode(ctx, req.(*SaveNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeleteNode(ctx, req.(*DeleteNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetEvents(ctx, req.(*GetEventsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hierarchy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Hierarchy",
	HandlerType: (*HierarchyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _Hierarchy_DeepPing_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Hierarchy_GetNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _Hierarchy_GetNodes_Handler,
		},
		{
			MethodName: "GetChildNodes",
			Handler:    _Hierarchy_GetChildNodes_Handler,
		},
		{
			MethodName: "GetParentNode",
			Handler:    _Hierarchy_GetParentNode_Handler,
		},
		{
			MethodName: "GetAncestors",
			Handler:    _Hierarchy_GetAncestors_Handler,
		},
		{
			MethodName: "GetNodeIdByOrigin",
			Handler:    _Hierarchy_GetNodeIdByOrigin_Handler,
		},
		{
			MethodName: "SaveNode",
			Handler:    _Hierarchy_SaveNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Hierarchy_DeleteNode_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Hierarchy_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hierarchy/grpcapi.proto",
}
