// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authorize/grpcapi.proto

package grpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/SKF/proto/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IsAuthorizedInput struct {
	UserId               string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action               string         `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource             *common.Origin `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IsAuthorizedInput) Reset()         { *m = IsAuthorizedInput{} }
func (m *IsAuthorizedInput) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedInput) ProtoMessage()    {}
func (*IsAuthorizedInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{0}
}
func (m *IsAuthorizedInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedInput.Unmarshal(m, b)
}
func (m *IsAuthorizedInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedInput.Marshal(b, m, deterministic)
}
func (dst *IsAuthorizedInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedInput.Merge(dst, src)
}
func (m *IsAuthorizedInput) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedInput.Size(m)
}
func (m *IsAuthorizedInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedInput.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedInput proto.InternalMessageInfo

func (m *IsAuthorizedInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *IsAuthorizedInput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *IsAuthorizedInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type IsAuthorizedOutput struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedOutput) Reset()         { *m = IsAuthorizedOutput{} }
func (m *IsAuthorizedOutput) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedOutput) ProtoMessage()    {}
func (*IsAuthorizedOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{1}
}
func (m *IsAuthorizedOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedOutput.Unmarshal(m, b)
}
func (m *IsAuthorizedOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedOutput.Marshal(b, m, deterministic)
}
func (dst *IsAuthorizedOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedOutput.Merge(dst, src)
}
func (m *IsAuthorizedOutput) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedOutput.Size(m)
}
func (m *IsAuthorizedOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedOutput.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedOutput proto.InternalMessageInfo

func (m *IsAuthorizedOutput) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type IsAuthorizedByEndpointInput struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedByEndpointInput) Reset()         { *m = IsAuthorizedByEndpointInput{} }
func (m *IsAuthorizedByEndpointInput) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedByEndpointInput) ProtoMessage()    {}
func (*IsAuthorizedByEndpointInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{2}
}
func (m *IsAuthorizedByEndpointInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedByEndpointInput.Unmarshal(m, b)
}
func (m *IsAuthorizedByEndpointInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedByEndpointInput.Marshal(b, m, deterministic)
}
func (dst *IsAuthorizedByEndpointInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedByEndpointInput.Merge(dst, src)
}
func (m *IsAuthorizedByEndpointInput) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedByEndpointInput.Size(m)
}
func (m *IsAuthorizedByEndpointInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedByEndpointInput.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedByEndpointInput proto.InternalMessageInfo

func (m *IsAuthorizedByEndpointInput) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *IsAuthorizedByEndpointInput) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *IsAuthorizedByEndpointInput) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *IsAuthorizedByEndpointInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type IsAuthorizedByEndpointOutput struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedByEndpointOutput) Reset()         { *m = IsAuthorizedByEndpointOutput{} }
func (m *IsAuthorizedByEndpointOutput) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedByEndpointOutput) ProtoMessage()    {}
func (*IsAuthorizedByEndpointOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{3}
}
func (m *IsAuthorizedByEndpointOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedByEndpointOutput.Unmarshal(m, b)
}
func (m *IsAuthorizedByEndpointOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedByEndpointOutput.Marshal(b, m, deterministic)
}
func (dst *IsAuthorizedByEndpointOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedByEndpointOutput.Merge(dst, src)
}
func (m *IsAuthorizedByEndpointOutput) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedByEndpointOutput.Size(m)
}
func (m *IsAuthorizedByEndpointOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedByEndpointOutput.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedByEndpointOutput proto.InternalMessageInfo

func (m *IsAuthorizedByEndpointOutput) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddResourceInput struct {
	Resource             *common.Origin `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddResourceInput) Reset()         { *m = AddResourceInput{} }
func (m *AddResourceInput) String() string { return proto.CompactTextString(m) }
func (*AddResourceInput) ProtoMessage()    {}
func (*AddResourceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{4}
}
func (m *AddResourceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResourceInput.Unmarshal(m, b)
}
func (m *AddResourceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResourceInput.Marshal(b, m, deterministic)
}
func (dst *AddResourceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResourceInput.Merge(dst, src)
}
func (m *AddResourceInput) XXX_Size() int {
	return xxx_messageInfo_AddResourceInput.Size(m)
}
func (m *AddResourceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResourceInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddResourceInput proto.InternalMessageInfo

func (m *AddResourceInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type RemoveResourceInput struct {
	Resource             *common.Origin `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveResourceInput) Reset()         { *m = RemoveResourceInput{} }
func (m *RemoveResourceInput) String() string { return proto.CompactTextString(m) }
func (*RemoveResourceInput) ProtoMessage()    {}
func (*RemoveResourceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{5}
}
func (m *RemoveResourceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResourceInput.Unmarshal(m, b)
}
func (m *RemoveResourceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResourceInput.Marshal(b, m, deterministic)
}
func (dst *RemoveResourceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResourceInput.Merge(dst, src)
}
func (m *RemoveResourceInput) XXX_Size() int {
	return xxx_messageInfo_RemoveResourceInput.Size(m)
}
func (m *RemoveResourceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResourceInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResourceInput proto.InternalMessageInfo

func (m *RemoveResourceInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type AddResourcesInput struct {
	Resource             []*common.Origin `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddResourcesInput) Reset()         { *m = AddResourcesInput{} }
func (m *AddResourcesInput) String() string { return proto.CompactTextString(m) }
func (*AddResourcesInput) ProtoMessage()    {}
func (*AddResourcesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{6}
}
func (m *AddResourcesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResourcesInput.Unmarshal(m, b)
}
func (m *AddResourcesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResourcesInput.Marshal(b, m, deterministic)
}
func (dst *AddResourcesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResourcesInput.Merge(dst, src)
}
func (m *AddResourcesInput) XXX_Size() int {
	return xxx_messageInfo_AddResourcesInput.Size(m)
}
func (m *AddResourcesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResourcesInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddResourcesInput proto.InternalMessageInfo

func (m *AddResourcesInput) GetResource() []*common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type RemoveResourcesInput struct {
	Resource             []*common.Origin `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RemoveResourcesInput) Reset()         { *m = RemoveResourcesInput{} }
func (m *RemoveResourcesInput) String() string { return proto.CompactTextString(m) }
func (*RemoveResourcesInput) ProtoMessage()    {}
func (*RemoveResourcesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{7}
}
func (m *RemoveResourcesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResourcesInput.Unmarshal(m, b)
}
func (m *RemoveResourcesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResourcesInput.Marshal(b, m, deterministic)
}
func (dst *RemoveResourcesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResourcesInput.Merge(dst, src)
}
func (m *RemoveResourcesInput) XXX_Size() int {
	return xxx_messageInfo_RemoveResourcesInput.Size(m)
}
func (m *RemoveResourcesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResourcesInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResourcesInput proto.InternalMessageInfo

func (m *RemoveResourcesInput) GetResource() []*common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type GetResourcesByTypeInput struct {
	ResourceType         string   `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesByTypeInput) Reset()         { *m = GetResourcesByTypeInput{} }
func (m *GetResourcesByTypeInput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesByTypeInput) ProtoMessage()    {}
func (*GetResourcesByTypeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{8}
}
func (m *GetResourcesByTypeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesByTypeInput.Unmarshal(m, b)
}
func (m *GetResourcesByTypeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesByTypeInput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesByTypeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesByTypeInput.Merge(dst, src)
}
func (m *GetResourcesByTypeInput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesByTypeInput.Size(m)
}
func (m *GetResourcesByTypeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesByTypeInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesByTypeInput proto.InternalMessageInfo

func (m *GetResourcesByTypeInput) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type GetResourcesByOriginAndTypeInput struct {
	OriginId             string   `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesByOriginAndTypeInput) Reset()         { *m = GetResourcesByOriginAndTypeInput{} }
func (m *GetResourcesByOriginAndTypeInput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesByOriginAndTypeInput) ProtoMessage()    {}
func (*GetResourcesByOriginAndTypeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{9}
}
func (m *GetResourcesByOriginAndTypeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesByOriginAndTypeInput.Unmarshal(m, b)
}
func (m *GetResourcesByOriginAndTypeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesByOriginAndTypeInput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesByOriginAndTypeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesByOriginAndTypeInput.Merge(dst, src)
}
func (m *GetResourcesByOriginAndTypeInput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesByOriginAndTypeInput.Size(m)
}
func (m *GetResourcesByOriginAndTypeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesByOriginAndTypeInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesByOriginAndTypeInput proto.InternalMessageInfo

func (m *GetResourcesByOriginAndTypeInput) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *GetResourcesByOriginAndTypeInput) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type GetUserIDsWithAccessToResourceInput struct {
	OriginId             string   `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDsWithAccessToResourceInput) Reset()         { *m = GetUserIDsWithAccessToResourceInput{} }
func (m *GetUserIDsWithAccessToResourceInput) String() string { return proto.CompactTextString(m) }
func (*GetUserIDsWithAccessToResourceInput) ProtoMessage()    {}
func (*GetUserIDsWithAccessToResourceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{10}
}
func (m *GetUserIDsWithAccessToResourceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceInput.Unmarshal(m, b)
}
func (m *GetUserIDsWithAccessToResourceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceInput.Marshal(b, m, deterministic)
}
func (dst *GetUserIDsWithAccessToResourceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDsWithAccessToResourceInput.Merge(dst, src)
}
func (m *GetUserIDsWithAccessToResourceInput) XXX_Size() int {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceInput.Size(m)
}
func (m *GetUserIDsWithAccessToResourceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDsWithAccessToResourceInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDsWithAccessToResourceInput proto.InternalMessageInfo

func (m *GetUserIDsWithAccessToResourceInput) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

type GetResourcesByTypeOutput struct {
	Resources            []*common.Origin `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetResourcesByTypeOutput) Reset()         { *m = GetResourcesByTypeOutput{} }
func (m *GetResourcesByTypeOutput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesByTypeOutput) ProtoMessage()    {}
func (*GetResourcesByTypeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{11}
}
func (m *GetResourcesByTypeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesByTypeOutput.Unmarshal(m, b)
}
func (m *GetResourcesByTypeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesByTypeOutput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesByTypeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesByTypeOutput.Merge(dst, src)
}
func (m *GetResourcesByTypeOutput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesByTypeOutput.Size(m)
}
func (m *GetResourcesByTypeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesByTypeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesByTypeOutput proto.InternalMessageInfo

func (m *GetResourcesByTypeOutput) GetResources() []*common.Origin {
	if m != nil {
		return m.Resources
	}
	return nil
}

type GetResourcesByOriginAndTypeOutput struct {
	Resources            []*common.Origin `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetResourcesByOriginAndTypeOutput) Reset()         { *m = GetResourcesByOriginAndTypeOutput{} }
func (m *GetResourcesByOriginAndTypeOutput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesByOriginAndTypeOutput) ProtoMessage()    {}
func (*GetResourcesByOriginAndTypeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{12}
}
func (m *GetResourcesByOriginAndTypeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesByOriginAndTypeOutput.Unmarshal(m, b)
}
func (m *GetResourcesByOriginAndTypeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesByOriginAndTypeOutput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesByOriginAndTypeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesByOriginAndTypeOutput.Merge(dst, src)
}
func (m *GetResourcesByOriginAndTypeOutput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesByOriginAndTypeOutput.Size(m)
}
func (m *GetResourcesByOriginAndTypeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesByOriginAndTypeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesByOriginAndTypeOutput proto.InternalMessageInfo

func (m *GetResourcesByOriginAndTypeOutput) GetResources() []*common.Origin {
	if m != nil {
		return m.Resources
	}
	return nil
}

type GetUserIDsWithAccessToResourceOutput struct {
	UserIds              []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDsWithAccessToResourceOutput) Reset()         { *m = GetUserIDsWithAccessToResourceOutput{} }
func (m *GetUserIDsWithAccessToResourceOutput) String() string { return proto.CompactTextString(m) }
func (*GetUserIDsWithAccessToResourceOutput) ProtoMessage()    {}
func (*GetUserIDsWithAccessToResourceOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{13}
}
func (m *GetUserIDsWithAccessToResourceOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceOutput.Unmarshal(m, b)
}
func (m *GetUserIDsWithAccessToResourceOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceOutput.Marshal(b, m, deterministic)
}
func (dst *GetUserIDsWithAccessToResourceOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDsWithAccessToResourceOutput.Merge(dst, src)
}
func (m *GetUserIDsWithAccessToResourceOutput) XXX_Size() int {
	return xxx_messageInfo_GetUserIDsWithAccessToResourceOutput.Size(m)
}
func (m *GetUserIDsWithAccessToResourceOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDsWithAccessToResourceOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDsWithAccessToResourceOutput proto.InternalMessageInfo

func (m *GetUserIDsWithAccessToResourceOutput) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type AddResourceRelationInput struct {
	Resource             *common.Origin `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Parent               *common.Origin `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddResourceRelationInput) Reset()         { *m = AddResourceRelationInput{} }
func (m *AddResourceRelationInput) String() string { return proto.CompactTextString(m) }
func (*AddResourceRelationInput) ProtoMessage()    {}
func (*AddResourceRelationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{14}
}
func (m *AddResourceRelationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResourceRelationInput.Unmarshal(m, b)
}
func (m *AddResourceRelationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResourceRelationInput.Marshal(b, m, deterministic)
}
func (dst *AddResourceRelationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResourceRelationInput.Merge(dst, src)
}
func (m *AddResourceRelationInput) XXX_Size() int {
	return xxx_messageInfo_AddResourceRelationInput.Size(m)
}
func (m *AddResourceRelationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResourceRelationInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddResourceRelationInput proto.InternalMessageInfo

func (m *AddResourceRelationInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *AddResourceRelationInput) GetParent() *common.Origin {
	if m != nil {
		return m.Parent
	}
	return nil
}

type RemoveResourceRelationInput struct {
	Resource             *common.Origin `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Parent               *common.Origin `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveResourceRelationInput) Reset()         { *m = RemoveResourceRelationInput{} }
func (m *RemoveResourceRelationInput) String() string { return proto.CompactTextString(m) }
func (*RemoveResourceRelationInput) ProtoMessage()    {}
func (*RemoveResourceRelationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{15}
}
func (m *RemoveResourceRelationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResourceRelationInput.Unmarshal(m, b)
}
func (m *RemoveResourceRelationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResourceRelationInput.Marshal(b, m, deterministic)
}
func (dst *RemoveResourceRelationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResourceRelationInput.Merge(dst, src)
}
func (m *RemoveResourceRelationInput) XXX_Size() int {
	return xxx_messageInfo_RemoveResourceRelationInput.Size(m)
}
func (m *RemoveResourceRelationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResourceRelationInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResourceRelationInput proto.InternalMessageInfo

func (m *RemoveResourceRelationInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *RemoveResourceRelationInput) GetParent() *common.Origin {
	if m != nil {
		return m.Parent
	}
	return nil
}

type AddResourceRelationsInput struct {
	Relation             []*AddResourceRelationInput `protobuf:"bytes,1,rep,name=relation,proto3" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AddResourceRelationsInput) Reset()         { *m = AddResourceRelationsInput{} }
func (m *AddResourceRelationsInput) String() string { return proto.CompactTextString(m) }
func (*AddResourceRelationsInput) ProtoMessage()    {}
func (*AddResourceRelationsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{16}
}
func (m *AddResourceRelationsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResourceRelationsInput.Unmarshal(m, b)
}
func (m *AddResourceRelationsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResourceRelationsInput.Marshal(b, m, deterministic)
}
func (dst *AddResourceRelationsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResourceRelationsInput.Merge(dst, src)
}
func (m *AddResourceRelationsInput) XXX_Size() int {
	return xxx_messageInfo_AddResourceRelationsInput.Size(m)
}
func (m *AddResourceRelationsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResourceRelationsInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddResourceRelationsInput proto.InternalMessageInfo

func (m *AddResourceRelationsInput) GetRelation() []*AddResourceRelationInput {
	if m != nil {
		return m.Relation
	}
	return nil
}

type RemoveResourceRelationsInput struct {
	Relation             []*RemoveResourceRelationInput `protobuf:"bytes,1,rep,name=relation,proto3" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RemoveResourceRelationsInput) Reset()         { *m = RemoveResourceRelationsInput{} }
func (m *RemoveResourceRelationsInput) String() string { return proto.CompactTextString(m) }
func (*RemoveResourceRelationsInput) ProtoMessage()    {}
func (*RemoveResourceRelationsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{17}
}
func (m *RemoveResourceRelationsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResourceRelationsInput.Unmarshal(m, b)
}
func (m *RemoveResourceRelationsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResourceRelationsInput.Marshal(b, m, deterministic)
}
func (dst *RemoveResourceRelationsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResourceRelationsInput.Merge(dst, src)
}
func (m *RemoveResourceRelationsInput) XXX_Size() int {
	return xxx_messageInfo_RemoveResourceRelationsInput.Size(m)
}
func (m *RemoveResourceRelationsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResourceRelationsInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResourceRelationsInput proto.InternalMessageInfo

func (m *RemoveResourceRelationsInput) GetRelation() []*RemoveResourceRelationInput {
	if m != nil {
		return m.Relation
	}
	return nil
}

type AddUserPermissionInput struct {
	UserId               string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action               string         `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource             *common.Origin `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddUserPermissionInput) Reset()         { *m = AddUserPermissionInput{} }
func (m *AddUserPermissionInput) String() string { return proto.CompactTextString(m) }
func (*AddUserPermissionInput) ProtoMessage()    {}
func (*AddUserPermissionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{18}
}
func (m *AddUserPermissionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserPermissionInput.Unmarshal(m, b)
}
func (m *AddUserPermissionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserPermissionInput.Marshal(b, m, deterministic)
}
func (dst *AddUserPermissionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserPermissionInput.Merge(dst, src)
}
func (m *AddUserPermissionInput) XXX_Size() int {
	return xxx_messageInfo_AddUserPermissionInput.Size(m)
}
func (m *AddUserPermissionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserPermissionInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserPermissionInput proto.InternalMessageInfo

func (m *AddUserPermissionInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddUserPermissionInput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AddUserPermissionInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type RemoveUserPermissionInput struct {
	UserId               string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action               string         `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource             *common.Origin `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveUserPermissionInput) Reset()         { *m = RemoveUserPermissionInput{} }
func (m *RemoveUserPermissionInput) String() string { return proto.CompactTextString(m) }
func (*RemoveUserPermissionInput) ProtoMessage()    {}
func (*RemoveUserPermissionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{19}
}
func (m *RemoveUserPermissionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserPermissionInput.Unmarshal(m, b)
}
func (m *RemoveUserPermissionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserPermissionInput.Marshal(b, m, deterministic)
}
func (dst *RemoveUserPermissionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserPermissionInput.Merge(dst, src)
}
func (m *RemoveUserPermissionInput) XXX_Size() int {
	return xxx_messageInfo_RemoveUserPermissionInput.Size(m)
}
func (m *RemoveUserPermissionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserPermissionInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserPermissionInput proto.InternalMessageInfo

func (m *RemoveUserPermissionInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RemoveUserPermissionInput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RemoveUserPermissionInput) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Action struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{20}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Action) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetActionsByUserRoleInput struct {
	UserRole             string   `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsByUserRoleInput) Reset()         { *m = GetActionsByUserRoleInput{} }
func (m *GetActionsByUserRoleInput) String() string { return proto.CompactTextString(m) }
func (*GetActionsByUserRoleInput) ProtoMessage()    {}
func (*GetActionsByUserRoleInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{21}
}
func (m *GetActionsByUserRoleInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsByUserRoleInput.Unmarshal(m, b)
}
func (m *GetActionsByUserRoleInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsByUserRoleInput.Marshal(b, m, deterministic)
}
func (dst *GetActionsByUserRoleInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsByUserRoleInput.Merge(dst, src)
}
func (m *GetActionsByUserRoleInput) XXX_Size() int {
	return xxx_messageInfo_GetActionsByUserRoleInput.Size(m)
}
func (m *GetActionsByUserRoleInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsByUserRoleInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsByUserRoleInput proto.InternalMessageInfo

func (m *GetActionsByUserRoleInput) GetUserRole() string {
	if m != nil {
		return m.UserRole
	}
	return ""
}

type GetActionsByUserRoleOutput struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetActionsByUserRoleOutput) Reset()         { *m = GetActionsByUserRoleOutput{} }
func (m *GetActionsByUserRoleOutput) String() string { return proto.CompactTextString(m) }
func (*GetActionsByUserRoleOutput) ProtoMessage()    {}
func (*GetActionsByUserRoleOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{22}
}
func (m *GetActionsByUserRoleOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsByUserRoleOutput.Unmarshal(m, b)
}
func (m *GetActionsByUserRoleOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsByUserRoleOutput.Marshal(b, m, deterministic)
}
func (dst *GetActionsByUserRoleOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsByUserRoleOutput.Merge(dst, src)
}
func (m *GetActionsByUserRoleOutput) XXX_Size() int {
	return xxx_messageInfo_GetActionsByUserRoleOutput.Size(m)
}
func (m *GetActionsByUserRoleOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsByUserRoleOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsByUserRoleOutput proto.InternalMessageInfo

func (m *GetActionsByUserRoleOutput) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ActionResource struct {
	ActionName           string         `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Resource             *common.Origin `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActionResource) Reset()         { *m = ActionResource{} }
func (m *ActionResource) String() string { return proto.CompactTextString(m) }
func (*ActionResource) ProtoMessage()    {}
func (*ActionResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{23}
}
func (m *ActionResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResource.Unmarshal(m, b)
}
func (m *ActionResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResource.Marshal(b, m, deterministic)
}
func (dst *ActionResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResource.Merge(dst, src)
}
func (m *ActionResource) XXX_Size() int {
	return xxx_messageInfo_ActionResource.Size(m)
}
func (m *ActionResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResource.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResource proto.InternalMessageInfo

func (m *ActionResource) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *ActionResource) GetResource() *common.Origin {
	if m != nil {
		return m.Resource
	}
	return nil
}

type GetResourcesAndActionsByUserInput struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesAndActionsByUserInput) Reset()         { *m = GetResourcesAndActionsByUserInput{} }
func (m *GetResourcesAndActionsByUserInput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesAndActionsByUserInput) ProtoMessage()    {}
func (*GetResourcesAndActionsByUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{24}
}
func (m *GetResourcesAndActionsByUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesAndActionsByUserInput.Unmarshal(m, b)
}
func (m *GetResourcesAndActionsByUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesAndActionsByUserInput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesAndActionsByUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesAndActionsByUserInput.Merge(dst, src)
}
func (m *GetResourcesAndActionsByUserInput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesAndActionsByUserInput.Size(m)
}
func (m *GetResourcesAndActionsByUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesAndActionsByUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesAndActionsByUserInput proto.InternalMessageInfo

func (m *GetResourcesAndActionsByUserInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetResourcesAndActionsByUserOutput struct {
	Data                 []*ActionResource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetResourcesAndActionsByUserOutput) Reset()         { *m = GetResourcesAndActionsByUserOutput{} }
func (m *GetResourcesAndActionsByUserOutput) String() string { return proto.CompactTextString(m) }
func (*GetResourcesAndActionsByUserOutput) ProtoMessage()    {}
func (*GetResourcesAndActionsByUserOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_9239f30930f167e9, []int{25}
}
func (m *GetResourcesAndActionsByUserOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesAndActionsByUserOutput.Unmarshal(m, b)
}
func (m *GetResourcesAndActionsByUserOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesAndActionsByUserOutput.Marshal(b, m, deterministic)
}
func (dst *GetResourcesAndActionsByUserOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesAndActionsByUserOutput.Merge(dst, src)
}
func (m *GetResourcesAndActionsByUserOutput) XXX_Size() int {
	return xxx_messageInfo_GetResourcesAndActionsByUserOutput.Size(m)
}
func (m *GetResourcesAndActionsByUserOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesAndActionsByUserOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesAndActionsByUserOutput proto.InternalMessageInfo

func (m *GetResourcesAndActionsByUserOutput) GetData() []*ActionResource {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*IsAuthorizedInput)(nil), "grpcapi.IsAuthorizedInput")
	proto.RegisterType((*IsAuthorizedOutput)(nil), "grpcapi.IsAuthorizedOutput")
	proto.RegisterType((*IsAuthorizedByEndpointInput)(nil), "grpcapi.IsAuthorizedByEndpointInput")
	proto.RegisterType((*IsAuthorizedByEndpointOutput)(nil), "grpcapi.IsAuthorizedByEndpointOutput")
	proto.RegisterType((*AddResourceInput)(nil), "grpcapi.AddResourceInput")
	proto.RegisterType((*RemoveResourceInput)(nil), "grpcapi.RemoveResourceInput")
	proto.RegisterType((*AddResourcesInput)(nil), "grpcapi.AddResourcesInput")
	proto.RegisterType((*RemoveResourcesInput)(nil), "grpcapi.RemoveResourcesInput")
	proto.RegisterType((*GetResourcesByTypeInput)(nil), "grpcapi.GetResourcesByTypeInput")
	proto.RegisterType((*GetResourcesByOriginAndTypeInput)(nil), "grpcapi.GetResourcesByOriginAndTypeInput")
	proto.RegisterType((*GetUserIDsWithAccessToResourceInput)(nil), "grpcapi.GetUserIDsWithAccessToResourceInput")
	proto.RegisterType((*GetResourcesByTypeOutput)(nil), "grpcapi.GetResourcesByTypeOutput")
	proto.RegisterType((*GetResourcesByOriginAndTypeOutput)(nil), "grpcapi.GetResourcesByOriginAndTypeOutput")
	proto.RegisterType((*GetUserIDsWithAccessToResourceOutput)(nil), "grpcapi.GetUserIDsWithAccessToResourceOutput")
	proto.RegisterType((*AddResourceRelationInput)(nil), "grpcapi.AddResourceRelationInput")
	proto.RegisterType((*RemoveResourceRelationInput)(nil), "grpcapi.RemoveResourceRelationInput")
	proto.RegisterType((*AddResourceRelationsInput)(nil), "grpcapi.AddResourceRelationsInput")
	proto.RegisterType((*RemoveResourceRelationsInput)(nil), "grpcapi.RemoveResourceRelationsInput")
	proto.RegisterType((*AddUserPermissionInput)(nil), "grpcapi.AddUserPermissionInput")
	proto.RegisterType((*RemoveUserPermissionInput)(nil), "grpcapi.RemoveUserPermissionInput")
	proto.RegisterType((*Action)(nil), "grpcapi.Action")
	proto.RegisterMapType((map[string]string)(nil), "grpcapi.Action.DataEntry")
	proto.RegisterType((*GetActionsByUserRoleInput)(nil), "grpcapi.GetActionsByUserRoleInput")
	proto.RegisterType((*GetActionsByUserRoleOutput)(nil), "grpcapi.GetActionsByUserRoleOutput")
	proto.RegisterType((*ActionResource)(nil), "grpcapi.ActionResource")
	proto.RegisterType((*GetResourcesAndActionsByUserInput)(nil), "grpcapi.GetResourcesAndActionsByUserInput")
	proto.RegisterType((*GetResourcesAndActionsByUserOutput)(nil), "grpcapi.GetResourcesAndActionsByUserOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorizeClient is the client API for Authorize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizeClient interface {
	DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error)
	IsAuthorized(ctx context.Context, in *IsAuthorizedInput, opts ...grpc.CallOption) (*IsAuthorizedOutput, error)
	IsAuthorizedByEndpoint(ctx context.Context, in *IsAuthorizedByEndpointInput, opts ...grpc.CallOption) (*IsAuthorizedByEndpointOutput, error)
	AddResource(ctx context.Context, in *AddResourceInput, opts ...grpc.CallOption) (*common.Void, error)
	RemoveResource(ctx context.Context, in *RemoveResourceInput, opts ...grpc.CallOption) (*common.Void, error)
	AddResources(ctx context.Context, in *AddResourcesInput, opts ...grpc.CallOption) (*common.Void, error)
	RemoveResources(ctx context.Context, in *RemoveResourcesInput, opts ...grpc.CallOption) (*common.Void, error)
	GetResourcesByType(ctx context.Context, in *GetResourcesByTypeInput, opts ...grpc.CallOption) (*GetResourcesByTypeOutput, error)
	GetActionsByUserRole(ctx context.Context, in *GetActionsByUserRoleInput, opts ...grpc.CallOption) (*GetActionsByUserRoleOutput, error)
	GetResourcesAndActionsByUser(ctx context.Context, in *GetResourcesAndActionsByUserInput, opts ...grpc.CallOption) (*GetResourcesAndActionsByUserOutput, error)
	GetResourcesByOriginAndType(ctx context.Context, in *GetResourcesByOriginAndTypeInput, opts ...grpc.CallOption) (*GetResourcesByOriginAndTypeOutput, error)
	GetUserIDsWithAccessToResource(ctx context.Context, in *GetUserIDsWithAccessToResourceInput, opts ...grpc.CallOption) (*GetUserIDsWithAccessToResourceOutput, error)
	AddResourceRelation(ctx context.Context, in *AddResourceRelationInput, opts ...grpc.CallOption) (*common.Void, error)
	RemoveResourceRelation(ctx context.Context, in *RemoveResourceRelationInput, opts ...grpc.CallOption) (*common.Void, error)
	AddResourceRelations(ctx context.Context, in *AddResourceRelationsInput, opts ...grpc.CallOption) (*common.Void, error)
	RemoveResourceRelations(ctx context.Context, in *RemoveResourceRelationsInput, opts ...grpc.CallOption) (*common.Void, error)
	AddUserPermission(ctx context.Context, in *AddUserPermissionInput, opts ...grpc.CallOption) (*common.Void, error)
	RemoveUserPermission(ctx context.Context, in *RemoveUserPermissionInput, opts ...grpc.CallOption) (*common.Void, error)
}

type authorizeClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizeClient(cc *grpc.ClientConn) AuthorizeClient {
	return &authorizeClient{cc}
}

func (c *authorizeClient) DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error) {
	out := new(common.PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) IsAuthorized(ctx context.Context, in *IsAuthorizedInput, opts ...grpc.CallOption) (*IsAuthorizedOutput, error) {
	out := new(IsAuthorizedOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/IsAuthorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) IsAuthorizedByEndpoint(ctx context.Context, in *IsAuthorizedByEndpointInput, opts ...grpc.CallOption) (*IsAuthorizedByEndpointOutput, error) {
	out := new(IsAuthorizedByEndpointOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/IsAuthorizedByEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) AddResource(ctx context.Context, in *AddResourceInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/AddResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) RemoveResource(ctx context.Context, in *RemoveResourceInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/RemoveResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) AddResources(ctx context.Context, in *AddResourcesInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/AddResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) RemoveResources(ctx context.Context, in *RemoveResourcesInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/RemoveResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) GetResourcesByType(ctx context.Context, in *GetResourcesByTypeInput, opts ...grpc.CallOption) (*GetResourcesByTypeOutput, error) {
	out := new(GetResourcesByTypeOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/GetResourcesByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) GetActionsByUserRole(ctx context.Context, in *GetActionsByUserRoleInput, opts ...grpc.CallOption) (*GetActionsByUserRoleOutput, error) {
	out := new(GetActionsByUserRoleOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/GetActionsByUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) GetResourcesAndActionsByUser(ctx context.Context, in *GetResourcesAndActionsByUserInput, opts ...grpc.CallOption) (*GetResourcesAndActionsByUserOutput, error) {
	out := new(GetResourcesAndActionsByUserOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/GetResourcesAndActionsByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) GetResourcesByOriginAndType(ctx context.Context, in *GetResourcesByOriginAndTypeInput, opts ...grpc.CallOption) (*GetResourcesByOriginAndTypeOutput, error) {
	out := new(GetResourcesByOriginAndTypeOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/GetResourcesByOriginAndType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) GetUserIDsWithAccessToResource(ctx context.Context, in *GetUserIDsWithAccessToResourceInput, opts ...grpc.CallOption) (*GetUserIDsWithAccessToResourceOutput, error) {
	out := new(GetUserIDsWithAccessToResourceOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/GetUserIDsWithAccessToResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) AddResourceRelation(ctx context.Context, in *AddResourceRelationInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/AddResourceRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) RemoveResourceRelation(ctx context.Context, in *RemoveResourceRelationInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/RemoveResourceRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) AddResourceRelations(ctx context.Context, in *AddResourceRelationsInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/AddResourceRelations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) RemoveResourceRelations(ctx context.Context, in *RemoveResourceRelationsInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/RemoveResourceRelations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) AddUserPermission(ctx context.Context, in *AddUserPermissionInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/AddUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) RemoveUserPermission(ctx context.Context, in *RemoveUserPermissionInput, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := c.cc.Invoke(ctx, "/grpcapi.Authorize/RemoveUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizeServer is the server API for Authorize service.
type AuthorizeServer interface {
	DeepPing(context.Context, *common.Void) (*common.PrimitiveString, error)
	IsAuthorized(context.Context, *IsAuthorizedInput) (*IsAuthorizedOutput, error)
	IsAuthorizedByEndpoint(context.Context, *IsAuthorizedByEndpointInput) (*IsAuthorizedByEndpointOutput, error)
	AddResource(context.Context, *AddResourceInput) (*common.Void, error)
	RemoveResource(context.Context, *RemoveResourceInput) (*common.Void, error)
	AddResources(context.Context, *AddResourcesInput) (*common.Void, error)
	RemoveResources(context.Context, *RemoveResourcesInput) (*common.Void, error)
	GetResourcesByType(context.Context, *GetResourcesByTypeInput) (*GetResourcesByTypeOutput, error)
	GetActionsByUserRole(context.Context, *GetActionsByUserRoleInput) (*GetActionsByUserRoleOutput, error)
	GetResourcesAndActionsByUser(context.Context, *GetResourcesAndActionsByUserInput) (*GetResourcesAndActionsByUserOutput, error)
	GetResourcesByOriginAndType(context.Context, *GetResourcesByOriginAndTypeInput) (*GetResourcesByOriginAndTypeOutput, error)
	GetUserIDsWithAccessToResource(context.Context, *GetUserIDsWithAccessToResourceInput) (*GetUserIDsWithAccessToResourceOutput, error)
	AddResourceRelation(context.Context, *AddResourceRelationInput) (*common.Void, error)
	RemoveResourceRelation(context.Context, *RemoveResourceRelationInput) (*common.Void, error)
	AddResourceRelations(context.Context, *AddResourceRelationsInput) (*common.Void, error)
	RemoveResourceRelations(context.Context, *RemoveResourceRelationsInput) (*common.Void, error)
	AddUserPermission(context.Context, *AddUserPermissionInput) (*common.Void, error)
	RemoveUserPermission(context.Context, *RemoveUserPermissionInput) (*common.Void, error)
}

func RegisterAuthorizeServer(s *grpc.Server, srv AuthorizeServer) {
	s.RegisterService(&_Authorize_serviceDesc, srv)
}

func _Authorize_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).DeepPing(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/IsAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).IsAuthorized(ctx, req.(*IsAuthorizedInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_IsAuthorizedByEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedByEndpointInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).IsAuthorizedByEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/IsAuthorizedByEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).IsAuthorizedByEndpoint(ctx, req.(*IsAuthorizedByEndpointInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_AddResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddResourceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).AddResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/AddResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).AddResource(ctx, req.(*AddResourceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_RemoveResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveResourceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).RemoveResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/RemoveResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).RemoveResource(ctx, req.(*RemoveResourceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_AddResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddResourcesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).AddResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/AddResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).AddResources(ctx, req.(*AddResourcesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_RemoveResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveResourcesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).RemoveResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/RemoveResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).RemoveResources(ctx, req.(*RemoveResourcesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_GetResourcesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesByTypeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetResourcesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/GetResourcesByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetResourcesByType(ctx, req.(*GetResourcesByTypeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_GetActionsByUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsByUserRoleInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetActionsByUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/GetActionsByUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetActionsByUserRole(ctx, req.(*GetActionsByUserRoleInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_GetResourcesAndActionsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesAndActionsByUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetResourcesAndActionsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/GetResourcesAndActionsByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetResourcesAndActionsByUser(ctx, req.(*GetResourcesAndActionsByUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_GetResourcesByOriginAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesByOriginAndTypeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetResourcesByOriginAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/GetResourcesByOriginAndType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetResourcesByOriginAndType(ctx, req.(*GetResourcesByOriginAndTypeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_GetUserIDsWithAccessToResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDsWithAccessToResourceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetUserIDsWithAccessToResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/GetUserIDsWithAccessToResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetUserIDsWithAccessToResource(ctx, req.(*GetUserIDsWithAccessToResourceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_AddResourceRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddResourceRelationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).AddResourceRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/AddResourceRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).AddResourceRelation(ctx, req.(*AddResourceRelationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_RemoveResourceRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveResourceRelationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).RemoveResourceRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/RemoveResourceRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).RemoveResourceRelation(ctx, req.(*RemoveResourceRelationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_AddResourceRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddResourceRelationsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).AddResourceRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/AddResourceRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).AddResourceRelations(ctx, req.(*AddResourceRelationsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_RemoveResourceRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveResourceRelationsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).RemoveResourceRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/RemoveResourceRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).RemoveResourceRelations(ctx, req.(*RemoveResourceRelationsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_AddUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserPermissionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).AddUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/AddUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).AddUserPermission(ctx, req.(*AddUserPermissionInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_RemoveUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserPermissionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).RemoveUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Authorize/RemoveUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).RemoveUserPermission(ctx, req.(*RemoveUserPermissionInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorize_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Authorize",
	HandlerType: (*AuthorizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _Authorize_DeepPing_Handler,
		},
		{
			MethodName: "IsAuthorized",
			Handler:    _Authorize_IsAuthorized_Handler,
		},
		{
			MethodName: "IsAuthorizedByEndpoint",
			Handler:    _Authorize_IsAuthorizedByEndpoint_Handler,
		},
		{
			MethodName: "AddResource",
			Handler:    _Authorize_AddResource_Handler,
		},
		{
			MethodName: "RemoveResource",
			Handler:    _Authorize_RemoveResource_Handler,
		},
		{
			MethodName: "AddResources",
			Handler:    _Authorize_AddResources_Handler,
		},
		{
			MethodName: "RemoveResources",
			Handler:    _Authorize_RemoveResources_Handler,
		},
		{
			MethodName: "GetResourcesByType",
			Handler:    _Authorize_GetResourcesByType_Handler,
		},
		{
			MethodName: "GetActionsByUserRole",
			Handler:    _Authorize_GetActionsByUserRole_Handler,
		},
		{
			MethodName: "GetResourcesAndActionsByUser",
			Handler:    _Authorize_GetResourcesAndActionsByUser_Handler,
		},
		{
			MethodName: "GetResourcesByOriginAndType",
			Handler:    _Authorize_GetResourcesByOriginAndType_Handler,
		},
		{
			MethodName: "GetUserIDsWithAccessToResource",
			Handler:    _Authorize_GetUserIDsWithAccessToResource_Handler,
		},
		{
			MethodName: "AddResourceRelation",
			Handler:    _Authorize_AddResourceRelation_Handler,
		},
		{
			MethodName: "RemoveResourceRelation",
			Handler:    _Authorize_RemoveResourceRelation_Handler,
		},
		{
			MethodName: "AddResourceRelations",
			Handler:    _Authorize_AddResourceRelations_Handler,
		},
		{
			MethodName: "RemoveResourceRelations",
			Handler:    _Authorize_RemoveResourceRelations_Handler,
		},
		{
			MethodName: "AddUserPermission",
			Handler:    _Authorize_AddUserPermission_Handler,
		},
		{
			MethodName: "RemoveUserPermission",
			Handler:    _Authorize_RemoveUserPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorize/grpcapi.proto",
}

func init() { proto.RegisterFile("authorize/grpcapi.proto", fileDescriptor_grpcapi_9239f30930f167e9) }

var fileDescriptor_grpcapi_9239f30930f167e9 = []byte{
	// 1026 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xef, 0x6e, 0xdb, 0x36,
	0x10, 0x8f, 0x9d, 0x2c, 0xb1, 0x2f, 0x59, 0xda, 0x32, 0x41, 0x6c, 0xcb, 0xde, 0x9a, 0x30, 0xe9,
	0xd0, 0xa6, 0xad, 0x0b, 0xb4, 0x1f, 0x16, 0x14, 0x5b, 0x56, 0x19, 0xc9, 0x52, 0x6f, 0x40, 0xeb,
	0xaa, 0xdd, 0x06, 0x6c, 0x18, 0x32, 0xcd, 0x22, 0x1c, 0x21, 0xb6, 0xa8, 0x49, 0x74, 0x30, 0x0d,
	0x03, 0xf6, 0x1a, 0x7b, 0x86, 0x3d, 0xda, 0x9e, 0x62, 0x90, 0x48, 0xd1, 0x94, 0x45, 0xc9, 0x59,
	0x80, 0xf6, 0x93, 0x45, 0xf2, 0xee, 0xf7, 0xbb, 0x3b, 0xf2, 0xfe, 0x18, 0x1a, 0xf6, 0x94, 0x5d,
	0xd0, 0xc0, 0xfd, 0x83, 0x3c, 0x19, 0x05, 0xfe, 0xd0, 0xf6, 0xdd, 0xae, 0x1f, 0x50, 0x46, 0xd1,
	0x9a, 0x58, 0x1a, 0x5b, 0x43, 0x3a, 0x99, 0x50, 0xef, 0x09, 0xff, 0xe1, 0xa7, 0xd8, 0x87, 0x3b,
	0xfd, 0xd0, 0x4c, 0x55, 0x9d, 0xbe, 0xe7, 0x4f, 0x19, 0x6a, 0xc0, 0xda, 0x34, 0x24, 0xc1, 0xb9,
	0xeb, 0x34, 0x2b, 0xbb, 0x95, 0xfb, 0x75, 0x6b, 0x35, 0x5e, 0xf6, 0x1d, 0xb4, 0x03, 0xab, 0xf6,
	0x90, 0xb9, 0xd4, 0x6b, 0x56, 0xf9, 0x3e, 0x5f, 0xa1, 0x43, 0xa8, 0x05, 0x24, 0xa4, 0xd3, 0x60,
	0x48, 0x9a, 0xcb, 0xbb, 0x95, 0xfb, 0xeb, 0x4f, 0x37, 0xbb, 0x82, 0xe6, 0x75, 0xe0, 0x8e, 0x5c,
	0xcf, 0x92, 0xe7, 0xf8, 0x00, 0x90, 0xca, 0xf8, 0x7a, 0xca, 0x62, 0xca, 0x4d, 0xa8, 0xd2, 0xcb,
	0x84, 0xad, 0x66, 0x55, 0xe9, 0x25, 0xfe, 0x13, 0xda, 0xaa, 0x54, 0x2f, 0x3a, 0xf5, 0x1c, 0x9f,
	0xba, 0x1e, 0xe3, 0x16, 0xde, 0x86, 0x65, 0xdb, 0x77, 0x85, 0x75, 0xf1, 0x67, 0x6c, 0xda, 0x84,
	0xb0, 0x0b, 0xea, 0xa4, 0xa6, 0xf1, 0x15, 0x32, 0xa0, 0x46, 0x84, 0x6a, 0x62, 0x5a, 0xdd, 0x92,
	0x6b, 0xd5, 0xcf, 0x15, 0xd5, 0x4f, 0xdc, 0x85, 0x8e, 0x9e, 0xbd, 0xc0, 0xda, 0x63, 0xb8, 0x6d,
	0x3a, 0x8e, 0x25, 0x5c, 0xe4, 0x26, 0xaa, 0x31, 0xa9, 0x2c, 0x88, 0x89, 0x09, 0x5b, 0x16, 0x99,
	0xd0, 0x2b, 0x72, 0x73, 0x88, 0xaf, 0xe0, 0x8e, 0x62, 0x42, 0xa8, 0x03, 0x58, 0x2e, 0x05, 0xe8,
	0xc1, 0x76, 0xd6, 0x86, 0x1b, 0x60, 0x1c, 0x43, 0xe3, 0x8c, 0x30, 0x09, 0xd0, 0x8b, 0xde, 0x45,
	0xbe, 0xf0, 0x65, 0x1f, 0x3e, 0x4e, 0xc5, 0xce, 0x59, 0xe4, 0x13, 0x71, 0x77, 0x1b, 0xe9, 0x66,
	0x2c, 0x89, 0x1d, 0xd8, 0xcd, 0xea, 0x73, 0x06, 0xd3, 0x73, 0x66, 0x40, 0x6d, 0xa8, 0xd3, 0x64,
	0x77, 0xf6, 0x3c, 0x6b, 0x7c, 0xa3, 0xef, 0xe4, 0x59, 0xaa, 0x1a, 0x96, 0x1e, 0xec, 0x9f, 0x11,
	0xf6, 0x5d, 0x7c, 0xd5, 0x27, 0xe1, 0x0f, 0x2e, 0xbb, 0x30, 0x87, 0x43, 0x12, 0x86, 0xef, 0x68,
	0x36, 0xfa, 0x65, 0x44, 0xf8, 0x25, 0x34, 0xf3, 0x9e, 0x8a, 0xd7, 0xf1, 0x08, 0xea, 0x29, 0x5f,
	0x58, 0x10, 0xb2, 0x99, 0x00, 0x7e, 0x03, 0x7b, 0x25, 0x3e, 0xdf, 0x08, 0xd2, 0x84, 0x83, 0x72,
	0x07, 0x05, 0x6a, 0x0b, 0x6a, 0xe2, 0xfd, 0x73, 0xd0, 0xba, 0xb5, 0xc6, 0x13, 0x20, 0xc4, 0x1e,
	0x34, 0x95, 0xe7, 0x64, 0x91, 0xb1, 0x1d, 0x27, 0xfa, 0xff, 0x7e, 0x96, 0xe8, 0x33, 0x58, 0xf5,
	0xed, 0x80, 0x78, 0x2c, 0xb9, 0x89, 0xbc, 0xa4, 0x38, 0xc5, 0xbf, 0x41, 0x3b, 0xfb, 0xfa, 0xde,
	0x3f, 0xe5, 0x8f, 0xd0, 0xd2, 0xb8, 0x28, 0x5e, 0xfd, 0x97, 0x31, 0x21, 0xdf, 0x11, 0xf1, 0xde,
	0xeb, 0xa6, 0x75, 0xb5, 0x28, 0x30, 0x96, 0x54, 0xc1, 0xbf, 0x40, 0x47, 0xef, 0x8e, 0x80, 0x7f,
	0x91, 0x83, 0x3f, 0x90, 0xf0, 0x25, 0x71, 0x50, 0x18, 0xa6, 0xb0, 0x63, 0x3a, 0x4e, 0x7c, 0xc7,
	0x03, 0x12, 0x4c, 0xdc, 0x30, 0x94, 0xb1, 0x7a, 0xaf, 0xd5, 0xfb, 0x77, 0x68, 0x71, 0xfb, 0x3e,
	0x38, 0xf3, 0xdf, 0x15, 0x58, 0x35, 0xb9, 0x1a, 0x82, 0x15, 0xcf, 0x9e, 0xa4, 0x25, 0x24, 0xf9,
	0x8e, 0xf7, 0x94, 0x84, 0x4f, 0xbe, 0xd1, 0x63, 0x58, 0x71, 0x6c, 0x66, 0x37, 0x97, 0x93, 0x08,
	0xb7, 0x66, 0x17, 0x98, 0xc0, 0x74, 0x4f, 0x6c, 0x66, 0x9f, 0x7a, 0x2c, 0x88, 0xac, 0x44, 0xcc,
	0xf8, 0x1c, 0xea, 0x72, 0x2b, 0xee, 0x30, 0x97, 0x24, 0x4a, 0x3b, 0xcc, 0x25, 0x89, 0xd0, 0x36,
	0x7c, 0x74, 0x65, 0x8f, 0xa7, 0x29, 0x05, 0x5f, 0x3c, 0xaf, 0x1e, 0x55, 0xf0, 0x11, 0xb4, 0xce,
	0x08, 0xe3, 0xa8, 0x61, 0x2f, 0x8a, 0x43, 0x63, 0xd1, 0xf1, 0xac, 0x8c, 0x24, 0x41, 0x09, 0xe8,
	0x38, 0xb5, 0x38, 0xc9, 0xba, 0x58, 0x02, 0x9f, 0x81, 0xa1, 0xd3, 0x14, 0xf9, 0xf9, 0x00, 0xd6,
	0x78, 0xa0, 0xd2, 0x9c, 0xbf, 0x35, 0xe7, 0x82, 0x95, 0x9e, 0xe3, 0x9f, 0x61, 0x53, 0x6c, 0xa5,
	0x69, 0x70, 0x17, 0xd6, 0xf9, 0xe1, 0xb9, 0x12, 0x2b, 0xe0, 0x5b, 0xaf, 0xe2, 0x88, 0xa9, 0xc1,
	0xaf, 0x2e, 0x08, 0xfe, 0x17, 0xd9, 0x22, 0x65, 0x7a, 0x4e, 0xc6, 0xe6, 0xf2, 0xeb, 0xc7, 0x6f,
	0x00, 0x97, 0x69, 0x0b, 0x6f, 0x1f, 0x8a, 0xdb, 0xe2, 0xae, 0x36, 0xe6, 0x5d, 0x4d, 0xf3, 0x21,
	0x11, 0x7a, 0xfa, 0xef, 0x3a, 0xd4, 0x65, 0x83, 0x46, 0xcf, 0xa0, 0x76, 0x42, 0x88, 0x3f, 0x70,
	0xbd, 0x11, 0xda, 0x48, 0x9d, 0xf8, 0x9e, 0xba, 0x8e, 0xd1, 0x48, 0x57, 0x83, 0xc0, 0x9d, 0xb8,
	0xcc, 0xbd, 0x22, 0x6f, 0x59, 0xe0, 0x7a, 0x23, 0xbc, 0x84, 0xfa, 0xb0, 0xa1, 0x36, 0x79, 0x64,
	0x48, 0xc6, 0xdc, 0x44, 0x64, 0xb4, 0xb5, 0x67, 0xdc, 0x70, 0xbc, 0x84, 0x46, 0xb0, 0xa3, 0x9f,
	0x17, 0xd0, 0x81, 0x56, 0x71, 0x6e, 0x9c, 0x31, 0xee, 0x2d, 0x90, 0x92, 0x44, 0x47, 0xb0, 0xae,
	0x54, 0x1f, 0xd4, 0xd2, 0xd5, 0x24, 0x0e, 0x99, 0x09, 0x03, 0x5e, 0x42, 0xc7, 0xb0, 0x99, 0x2d,
	0x2c, 0xa8, 0x53, 0x50, 0x71, 0xf4, 0xfa, 0xcf, 0x61, 0x43, 0x9d, 0x2f, 0x94, 0x68, 0xe5, 0xc6,
	0x8e, 0x9c, 0xee, 0x0b, 0xb8, 0x35, 0x37, 0x5a, 0xa0, 0x4f, 0x0a, 0xc8, 0x0b, 0x10, 0x7e, 0x02,
	0x94, 0x6f, 0xb7, 0x68, 0x57, 0x82, 0x14, 0x4c, 0x1d, 0xc6, 0x5e, 0x89, 0x84, 0x0c, 0xaa, 0x0d,
	0xdb, 0xba, 0x24, 0x44, 0x58, 0x55, 0xd6, 0x67, 0xb7, 0xb1, 0x5f, 0x2a, 0x23, 0x29, 0x22, 0xe8,
	0x94, 0x65, 0x00, 0x3a, 0xd4, 0xda, 0xa9, 0x4d, 0x33, 0xe3, 0xe1, 0xb5, 0x64, 0x25, 0xf5, 0x15,
	0xb4, 0x4b, 0xe6, 0x0b, 0xf4, 0xa0, 0x20, 0x42, 0xf9, 0xc9, 0xcb, 0x38, 0xbc, 0x8e, 0xa8, 0xe4,
	0xfd, 0x0b, 0x3e, 0x2d, 0x1f, 0x42, 0xd0, 0x23, 0x15, 0x6f, 0xd1, 0x38, 0x66, 0x3c, 0xbe, 0xa6,
	0xb4, 0x34, 0xe0, 0x25, 0x6c, 0x69, 0x3a, 0x35, 0x5a, 0xdc, 0xc7, 0x73, 0xaf, 0xef, 0x15, 0xec,
	0xe8, 0x9b, 0x32, 0xba, 0x56, 0xd7, 0xce, 0xe1, 0x7d, 0x03, 0xdb, 0xba, 0xc9, 0x43, 0x79, 0x70,
	0x85, 0x83, 0x49, 0x0e, 0x6b, 0x00, 0x8d, 0x82, 0x49, 0x03, 0xdd, 0x5b, 0x60, 0x5c, 0x01, 0xe2,
	0x49, 0xf2, 0x4f, 0x22, 0xdb, 0xdf, 0xd1, 0x5d, 0xd5, 0x34, 0x4d, 0xef, 0xd7, 0xf9, 0xa8, 0x1b,
	0x14, 0x14, 0x1f, 0x0b, 0xe7, 0x88, 0x79, 0xac, 0x5e, 0xe7, 0x9f, 0x6a, 0xeb, 0xed, 0xb7, 0x5f,
	0x77, 0x4f, 0xbd, 0xb1, 0x3b, 0xba, 0x60, 0x5d, 0x73, 0xd0, 0xef, 0xca, 0x32, 0xf9, 0xeb, 0x6a,
	0xf2, 0x4f, 0xf6, 0xd9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0x68, 0x77, 0x96, 0x02, 0x0f,
	0x00, 0x00,
}
