// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mhub/grpcapi.proto

package mhubapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskStatus int32

const (
	TaskStatus_NOT_SENT  TaskStatus = 0
	TaskStatus_SENT      TaskStatus = 1
	TaskStatus_RECEIVED  TaskStatus = 2
	TaskStatus_COMPLETED TaskStatus = 3
)

var TaskStatus_name = map[int32]string{
	0: "NOT_SENT",
	1: "SENT",
	2: "RECEIVED",
	3: "COMPLETED",
}
var TaskStatus_value = map[string]int32{
	"NOT_SENT":  0,
	"SENT":      1,
	"RECEIVED":  2,
	"COMPLETED": 3,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{0}
}

type AvailableDSKFStreamInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableDSKFStreamInput) Reset()         { *m = AvailableDSKFStreamInput{} }
func (m *AvailableDSKFStreamInput) String() string { return proto.CompactTextString(m) }
func (*AvailableDSKFStreamInput) ProtoMessage()    {}
func (*AvailableDSKFStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{0}
}
func (m *AvailableDSKFStreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableDSKFStreamInput.Unmarshal(m, b)
}
func (m *AvailableDSKFStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableDSKFStreamInput.Marshal(b, m, deterministic)
}
func (dst *AvailableDSKFStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableDSKFStreamInput.Merge(dst, src)
}
func (m *AvailableDSKFStreamInput) XXX_Size() int {
	return xxx_messageInfo_AvailableDSKFStreamInput.Size(m)
}
func (m *AvailableDSKFStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableDSKFStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableDSKFStreamInput proto.InternalMessageInfo

type AvailableDSKFStreamOutput struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DskfFile             string   `protobuf:"bytes,2,opt,name=dskf_file,json=dskfFile,proto3" json:"dskf_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableDSKFStreamOutput) Reset()         { *m = AvailableDSKFStreamOutput{} }
func (m *AvailableDSKFStreamOutput) String() string { return proto.CompactTextString(m) }
func (*AvailableDSKFStreamOutput) ProtoMessage()    {}
func (*AvailableDSKFStreamOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{1}
}
func (m *AvailableDSKFStreamOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableDSKFStreamOutput.Unmarshal(m, b)
}
func (m *AvailableDSKFStreamOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableDSKFStreamOutput.Marshal(b, m, deterministic)
}
func (dst *AvailableDSKFStreamOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableDSKFStreamOutput.Merge(dst, src)
}
func (m *AvailableDSKFStreamOutput) XXX_Size() int {
	return xxx_messageInfo_AvailableDSKFStreamOutput.Size(m)
}
func (m *AvailableDSKFStreamOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableDSKFStreamOutput.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableDSKFStreamOutput proto.InternalMessageInfo

func (m *AvailableDSKFStreamOutput) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *AvailableDSKFStreamOutput) GetDskfFile() string {
	if m != nil {
		return m.DskfFile
	}
	return ""
}

type SetTaskStatusInput struct {
	TaskId               string     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId               string     `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status               TaskStatus `protobuf:"varint,3,opt,name=status,proto3,enum=mhubapi.TaskStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetTaskStatusInput) Reset()         { *m = SetTaskStatusInput{} }
func (m *SetTaskStatusInput) String() string { return proto.CompactTextString(m) }
func (*SetTaskStatusInput) ProtoMessage()    {}
func (*SetTaskStatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{2}
}
func (m *SetTaskStatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTaskStatusInput.Unmarshal(m, b)
}
func (m *SetTaskStatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTaskStatusInput.Marshal(b, m, deterministic)
}
func (dst *SetTaskStatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTaskStatusInput.Merge(dst, src)
}
func (m *SetTaskStatusInput) XXX_Size() int {
	return xxx_messageInfo_SetTaskStatusInput.Size(m)
}
func (m *SetTaskStatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTaskStatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_SetTaskStatusInput proto.InternalMessageInfo

func (m *SetTaskStatusInput) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *SetTaskStatusInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetTaskStatusInput) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_NOT_SENT
}

type DeepPingOutput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeepPingOutput) Reset()         { *m = DeepPingOutput{} }
func (m *DeepPingOutput) String() string { return proto.CompactTextString(m) }
func (*DeepPingOutput) ProtoMessage()    {}
func (*DeepPingOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{3}
}
func (m *DeepPingOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeepPingOutput.Unmarshal(m, b)
}
func (m *DeepPingOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeepPingOutput.Marshal(b, m, deterministic)
}
func (dst *DeepPingOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeepPingOutput.Merge(dst, src)
}
func (m *DeepPingOutput) XXX_Size() int {
	return xxx_messageInfo_DeepPingOutput.Size(m)
}
func (m *DeepPingOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeepPingOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DeepPingOutput proto.InternalMessageInfo

func (m *DeepPingOutput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_8f0202804c3746df, []int{4}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AvailableDSKFStreamInput)(nil), "mhubapi.AvailableDSKFStreamInput")
	proto.RegisterType((*AvailableDSKFStreamOutput)(nil), "mhubapi.AvailableDSKFStreamOutput")
	proto.RegisterType((*SetTaskStatusInput)(nil), "mhubapi.SetTaskStatusInput")
	proto.RegisterType((*DeepPingOutput)(nil), "mhubapi.DeepPingOutput")
	proto.RegisterType((*Void)(nil), "mhubapi.Void")
	proto.RegisterEnum("mhubapi.TaskStatus", TaskStatus_name, TaskStatus_value)
}

func init() { proto.RegisterFile("mhub/grpcapi.proto", fileDescriptor_grpcapi_8f0202804c3746df) }

var fileDescriptor_grpcapi_8f0202804c3746df = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0xae, 0x9a, 0x40,
	0x14, 0x15, 0xdf, 0x2b, 0xe2, 0x4d, 0x7d, 0x21, 0xf3, 0x9a, 0xc8, 0xc3, 0x2e, 0xec, 0x2c, 0x1a,
	0xd3, 0x26, 0xb4, 0xb1, 0xdd, 0x76, 0x61, 0x05, 0x53, 0x62, 0x55, 0x2a, 0xc4, 0xad, 0x1d, 0x64,
	0xc4, 0x89, 0x28, 0x04, 0x66, 0x4c, 0xfb, 0x4b, 0xfd, 0xb3, 0xfe, 0x45, 0x03, 0x22, 0xc6, 0x54,
	0xdf, 0x6e, 0xce, 0xbd, 0x27, 0xe7, 0x9c, 0x7b, 0xef, 0x00, 0xda, 0x6d, 0x84, 0xff, 0x21, 0x4c,
	0x93, 0x15, 0x49, 0x98, 0x91, 0xa4, 0x31, 0x8f, 0x51, 0x23, 0xaf, 0x91, 0x84, 0x61, 0x1d, 0xb4,
	0xc1, 0x81, 0xb0, 0x88, 0xf8, 0x11, 0x35, 0xdd, 0xf1, 0xc8, 0xe5, 0x29, 0x25, 0x3b, 0x7b, 0x9f,
	0x08, 0x8e, 0x7f, 0xc0, 0xd3, 0x95, 0xde, 0x4c, 0xf0, 0x44, 0x70, 0xd4, 0x86, 0x06, 0x27, 0xd9,
	0x76, 0xc9, 0x02, 0x4d, 0xea, 0x4a, 0xbd, 0xe6, 0x5c, 0xce, 0xa1, 0x1d, 0xa0, 0x0e, 0x34, 0x83,
	0x6c, 0xbb, 0x5e, 0xae, 0x59, 0x44, 0xb5, 0x7a, 0xd1, 0x52, 0xf2, 0xc2, 0x88, 0x45, 0x14, 0x67,
	0x80, 0x5c, 0xca, 0x3d, 0x92, 0x6d, 0x5d, 0x4e, 0xb8, 0xc8, 0x0a, 0xa3, 0xdb, 0x5a, 0x6d, 0x68,
	0x88, 0x8c, 0xa6, 0x79, 0xe3, 0xa8, 0x24, 0xe7, 0xd0, 0x0e, 0xd0, 0x7b, 0x90, 0xb3, 0x42, 0x40,
	0xbb, 0xeb, 0x4a, 0xbd, 0x87, 0xfe, 0xa3, 0x51, 0x0e, 0x64, 0x9c, 0xb5, 0xe7, 0x25, 0x05, 0xbf,
	0x85, 0x07, 0x93, 0xd2, 0xc4, 0x61, 0xfb, 0xb0, 0x0c, 0xff, 0x0a, 0x5e, 0x1c, 0x48, 0x24, 0x68,
	0x69, 0x77, 0x04, 0x58, 0x86, 0xfb, 0x45, 0xcc, 0x82, 0x77, 0x03, 0x80, 0xb3, 0x0a, 0x7a, 0x09,
	0xca, 0x74, 0xe6, 0x2d, 0x5d, 0x6b, 0xea, 0xa9, 0x35, 0xa4, 0xc0, 0x7d, 0xf1, 0x92, 0xf2, 0xfa,
	0xdc, 0x1a, 0x5a, 0xf6, 0xc2, 0x32, 0xd5, 0x3a, 0x6a, 0x41, 0x73, 0x38, 0x9b, 0x38, 0xdf, 0x2d,
	0xcf, 0x32, 0xd5, 0xbb, 0xfe, 0x5f, 0x09, 0xd4, 0x09, 0x5b, 0xa5, 0x71, 0x14, 0x87, 0x4e, 0x1a,
	0xff, 0xfa, 0xfd, 0x4d, 0xf8, 0xe8, 0x33, 0x28, 0xa7, 0x1c, 0xa8, 0x55, 0x05, 0xce, 0x2d, 0xf5,
	0x76, 0x05, 0x2f, 0x93, 0xe2, 0x1a, 0xfa, 0x02, 0xad, 0x8b, 0x95, 0xa1, 0x4e, 0xc5, 0xfd, 0x7f,
	0x95, 0xfa, 0xa5, 0x2e, 0xae, 0xa1, 0x9f, 0xf0, 0x78, 0xe5, 0x88, 0xe8, 0x4d, 0xc5, 0xbb, 0x75,
	0x7e, 0x1d, 0x3f, 0x47, 0x39, 0xc5, 0xfb, 0x28, 0x7d, 0x7d, 0xfd, 0xa7, 0xfe, 0xe4, 0x8e, 0x47,
	0x86, 0xb5, 0x8f, 0x58, 0xb8, 0xe1, 0xc6, 0xc0, 0xb1, 0x8d, 0xc9, 0x69, 0x68, 0x5f, 0x2e, 0x3e,
	0xdc, 0xa7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xb7, 0x21, 0x7f, 0x86, 0x02, 0x00, 0x00,
}
