# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcapi.proto',
  package='pasapi',
  syntax='proto3',
  serialized_pb=_b('\n\rgrpcapi.proto\x12\x06pasapi\"\x1f\n\x0e\x44\x65\x65pPingOutput\x12\r\n\x05value\x18\x01 \x01(\t\"Q\n\x13SetPointStatusInput\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12)\n\x0c\x61larm_status\x18\x02 \x01(\x0e\x32\x13.pasapi.AlarmStatus\"\x16\n\x14SetPointStatusOutput\"&\n\x13GetPointStatusInput\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"A\n\x14GetPointStatusOutput\x12)\n\x0c\x61larm_status\x18\x01 \x01(\x0e\x32\x13.pasapi.AlarmStatus\"\x1b\n\x19GetPointStatusStreamInput\"X\n\x1aGetPointStatusStreamOutput\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12)\n\x0c\x61larm_status\x18\x02 \x01(\x0e\x32\x13.pasapi.AlarmStatus\"\x06\n\x04Void*O\n\x0b\x41larmStatus\x12\x12\n\x0eNOT_CONFIGURED\x10\x00\x12\x0b\n\x07NO_DATA\x10\x01\x12\x08\n\x04GOOD\x10\x02\x12\t\n\x05\x41LERT\x10\x03\x12\n\n\x06\x44\x41NGER\x10\x04\x32\xc7\x02\n\x10PointAlarmStatus\x12\x32\n\x08\x44\x65\x65pPing\x12\x0c.pasapi.Void\x1a\x16.pasapi.DeepPingOutput\"\x00\x12M\n\x0eSetPointStatus\x12\x1b.pasapi.SetPointStatusInput\x1a\x1c.pasapi.SetPointStatusOutput\"\x00\x12M\n\x0eGetPointStatus\x12\x1b.pasapi.GetPointStatusInput\x1a\x1c.pasapi.GetPointStatusOutput\"\x00\x12\x61\n\x14GetPointStatusStream\x12!.pasapi.GetPointStatusStreamInput\x1a\".pasapi.GetPointStatusStreamOutput\"\x00\x30\x01\x42\x16\xaa\x02\x13SKF.Enlight.API.PASb\x06proto3')
)

_ALARMSTATUS = _descriptor.EnumDescriptor(
  name='AlarmStatus',
  full_name='pasapi.AlarmStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_CONFIGURED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_DATA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DANGER', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=399,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_ALARMSTATUS)

AlarmStatus = enum_type_wrapper.EnumTypeWrapper(_ALARMSTATUS)
NOT_CONFIGURED = 0
NO_DATA = 1
GOOD = 2
ALERT = 3
DANGER = 4



_DEEPPINGOUTPUT = _descriptor.Descriptor(
  name='DeepPingOutput',
  full_name='pasapi.DeepPingOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='pasapi.DeepPingOutput.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=56,
)


_SETPOINTSTATUSINPUT = _descriptor.Descriptor(
  name='SetPointStatusInput',
  full_name='pasapi.SetPointStatusInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='pasapi.SetPointStatusInput.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_status', full_name='pasapi.SetPointStatusInput.alarm_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=139,
)


_SETPOINTSTATUSOUTPUT = _descriptor.Descriptor(
  name='SetPointStatusOutput',
  full_name='pasapi.SetPointStatusOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=163,
)


_GETPOINTSTATUSINPUT = _descriptor.Descriptor(
  name='GetPointStatusInput',
  full_name='pasapi.GetPointStatusInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='pasapi.GetPointStatusInput.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=203,
)


_GETPOINTSTATUSOUTPUT = _descriptor.Descriptor(
  name='GetPointStatusOutput',
  full_name='pasapi.GetPointStatusOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarm_status', full_name='pasapi.GetPointStatusOutput.alarm_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=270,
)


_GETPOINTSTATUSSTREAMINPUT = _descriptor.Descriptor(
  name='GetPointStatusStreamInput',
  full_name='pasapi.GetPointStatusStreamInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=299,
)


_GETPOINTSTATUSSTREAMOUTPUT = _descriptor.Descriptor(
  name='GetPointStatusStreamOutput',
  full_name='pasapi.GetPointStatusStreamOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='pasapi.GetPointStatusStreamOutput.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_status', full_name='pasapi.GetPointStatusStreamOutput.alarm_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=389,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='pasapi.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=397,
)

_SETPOINTSTATUSINPUT.fields_by_name['alarm_status'].enum_type = _ALARMSTATUS
_GETPOINTSTATUSOUTPUT.fields_by_name['alarm_status'].enum_type = _ALARMSTATUS
_GETPOINTSTATUSSTREAMOUTPUT.fields_by_name['alarm_status'].enum_type = _ALARMSTATUS
DESCRIPTOR.message_types_by_name['DeepPingOutput'] = _DEEPPINGOUTPUT
DESCRIPTOR.message_types_by_name['SetPointStatusInput'] = _SETPOINTSTATUSINPUT
DESCRIPTOR.message_types_by_name['SetPointStatusOutput'] = _SETPOINTSTATUSOUTPUT
DESCRIPTOR.message_types_by_name['GetPointStatusInput'] = _GETPOINTSTATUSINPUT
DESCRIPTOR.message_types_by_name['GetPointStatusOutput'] = _GETPOINTSTATUSOUTPUT
DESCRIPTOR.message_types_by_name['GetPointStatusStreamInput'] = _GETPOINTSTATUSSTREAMINPUT
DESCRIPTOR.message_types_by_name['GetPointStatusStreamOutput'] = _GETPOINTSTATUSSTREAMOUTPUT
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.enum_types_by_name['AlarmStatus'] = _ALARMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeepPingOutput = _reflection.GeneratedProtocolMessageType('DeepPingOutput', (_message.Message,), dict(
  DESCRIPTOR = _DEEPPINGOUTPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.DeepPingOutput)
  ))
_sym_db.RegisterMessage(DeepPingOutput)

SetPointStatusInput = _reflection.GeneratedProtocolMessageType('SetPointStatusInput', (_message.Message,), dict(
  DESCRIPTOR = _SETPOINTSTATUSINPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.SetPointStatusInput)
  ))
_sym_db.RegisterMessage(SetPointStatusInput)

SetPointStatusOutput = _reflection.GeneratedProtocolMessageType('SetPointStatusOutput', (_message.Message,), dict(
  DESCRIPTOR = _SETPOINTSTATUSOUTPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.SetPointStatusOutput)
  ))
_sym_db.RegisterMessage(SetPointStatusOutput)

GetPointStatusInput = _reflection.GeneratedProtocolMessageType('GetPointStatusInput', (_message.Message,), dict(
  DESCRIPTOR = _GETPOINTSTATUSINPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.GetPointStatusInput)
  ))
_sym_db.RegisterMessage(GetPointStatusInput)

GetPointStatusOutput = _reflection.GeneratedProtocolMessageType('GetPointStatusOutput', (_message.Message,), dict(
  DESCRIPTOR = _GETPOINTSTATUSOUTPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.GetPointStatusOutput)
  ))
_sym_db.RegisterMessage(GetPointStatusOutput)

GetPointStatusStreamInput = _reflection.GeneratedProtocolMessageType('GetPointStatusStreamInput', (_message.Message,), dict(
  DESCRIPTOR = _GETPOINTSTATUSSTREAMINPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.GetPointStatusStreamInput)
  ))
_sym_db.RegisterMessage(GetPointStatusStreamInput)

GetPointStatusStreamOutput = _reflection.GeneratedProtocolMessageType('GetPointStatusStreamOutput', (_message.Message,), dict(
  DESCRIPTOR = _GETPOINTSTATUSSTREAMOUTPUT,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.GetPointStatusStreamOutput)
  ))
_sym_db.RegisterMessage(GetPointStatusStreamOutput)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:pasapi.Void)
  ))
_sym_db.RegisterMessage(Void)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\023SKF.Enlight.API.PAS'))

_POINTALARMSTATUS = _descriptor.ServiceDescriptor(
  name='PointAlarmStatus',
  full_name='pasapi.PointAlarmStatus',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=481,
  serialized_end=808,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeepPing',
    full_name='pasapi.PointAlarmStatus.DeepPing',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_DEEPPINGOUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPointStatus',
    full_name='pasapi.PointAlarmStatus.SetPointStatus',
    index=1,
    containing_service=None,
    input_type=_SETPOINTSTATUSINPUT,
    output_type=_SETPOINTSTATUSOUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPointStatus',
    full_name='pasapi.PointAlarmStatus.GetPointStatus',
    index=2,
    containing_service=None,
    input_type=_GETPOINTSTATUSINPUT,
    output_type=_GETPOINTSTATUSOUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPointStatusStream',
    full_name='pasapi.PointAlarmStatus.GetPointStatusStream',
    index=3,
    containing_service=None,
    input_type=_GETPOINTSTATUSSTREAMINPUT,
    output_type=_GETPOINTSTATUSSTREAMOUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POINTALARMSTATUS)

DESCRIPTOR.services_by_name['PointAlarmStatus'] = _POINTALARMSTATUS

# @@protoc_insertion_point(module_scope)
