// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam/grpcapi.proto

package grpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/SKF/proto/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserClaims struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EulaAgreedDate       string   `protobuf:"bytes,3,opt,name=eula_agreed_date,json=eulaAgreedDate,proto3" json:"eula_agreed_date,omitempty"`
	ValidEula            string   `protobuf:"bytes,4,opt,name=valid_eula,json=validEula,proto3" json:"valid_eula,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	UserStatus           string   `protobuf:"bytes,6,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	UserRoles            string   `protobuf:"bytes,7,opt,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	UserAccess           string   `protobuf:"bytes,8,opt,name=user_access,json=userAccess,proto3" json:"user_access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserClaims) Reset()         { *m = UserClaims{} }
func (m *UserClaims) String() string { return proto.CompactTextString(m) }
func (*UserClaims) ProtoMessage()    {}
func (*UserClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{0}
}
func (m *UserClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserClaims.Unmarshal(m, b)
}
func (m *UserClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserClaims.Marshal(b, m, deterministic)
}
func (dst *UserClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserClaims.Merge(dst, src)
}
func (m *UserClaims) XXX_Size() int {
	return xxx_messageInfo_UserClaims.Size(m)
}
func (m *UserClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_UserClaims.DiscardUnknown(m)
}

var xxx_messageInfo_UserClaims proto.InternalMessageInfo

func (m *UserClaims) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserClaims) GetEulaAgreedDate() string {
	if m != nil {
		return m.EulaAgreedDate
	}
	return ""
}

func (m *UserClaims) GetValidEula() string {
	if m != nil {
		return m.ValidEula
	}
	return ""
}

func (m *UserClaims) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserClaims) GetUserStatus() string {
	if m != nil {
		return m.UserStatus
	}
	return ""
}

func (m *UserClaims) GetUserRoles() string {
	if m != nil {
		return m.UserRoles
	}
	return ""
}

func (m *UserClaims) GetUserAccess() string {
	if m != nil {
		return m.UserAccess
	}
	return ""
}

// Input & output messages
type GetHierarchyRelationsInput struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHierarchyRelationsInput) Reset()         { *m = GetHierarchyRelationsInput{} }
func (m *GetHierarchyRelationsInput) String() string { return proto.CompactTextString(m) }
func (*GetHierarchyRelationsInput) ProtoMessage()    {}
func (*GetHierarchyRelationsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{1}
}
func (m *GetHierarchyRelationsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHierarchyRelationsInput.Unmarshal(m, b)
}
func (m *GetHierarchyRelationsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHierarchyRelationsInput.Marshal(b, m, deterministic)
}
func (dst *GetHierarchyRelationsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHierarchyRelationsInput.Merge(dst, src)
}
func (m *GetHierarchyRelationsInput) XXX_Size() int {
	return xxx_messageInfo_GetHierarchyRelationsInput.Size(m)
}
func (m *GetHierarchyRelationsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHierarchyRelationsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetHierarchyRelationsInput proto.InternalMessageInfo

func (m *GetHierarchyRelationsInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetHierarchyRelationsOutput struct {
	NodeIds              []string `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHierarchyRelationsOutput) Reset()         { *m = GetHierarchyRelationsOutput{} }
func (m *GetHierarchyRelationsOutput) String() string { return proto.CompactTextString(m) }
func (*GetHierarchyRelationsOutput) ProtoMessage()    {}
func (*GetHierarchyRelationsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{2}
}
func (m *GetHierarchyRelationsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHierarchyRelationsOutput.Unmarshal(m, b)
}
func (m *GetHierarchyRelationsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHierarchyRelationsOutput.Marshal(b, m, deterministic)
}
func (dst *GetHierarchyRelationsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHierarchyRelationsOutput.Merge(dst, src)
}
func (m *GetHierarchyRelationsOutput) XXX_Size() int {
	return xxx_messageInfo_GetHierarchyRelationsOutput.Size(m)
}
func (m *GetHierarchyRelationsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHierarchyRelationsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetHierarchyRelationsOutput proto.InternalMessageInfo

func (m *GetHierarchyRelationsOutput) GetNodeIds() []string {
	if m != nil {
		return m.NodeIds
	}
	return nil
}

type CheckAuthenticationInput struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MethodArn            string   `protobuf:"bytes,2,opt,name=methodArn,proto3" json:"methodArn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthenticationInput) Reset()         { *m = CheckAuthenticationInput{} }
func (m *CheckAuthenticationInput) String() string { return proto.CompactTextString(m) }
func (*CheckAuthenticationInput) ProtoMessage()    {}
func (*CheckAuthenticationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{3}
}
func (m *CheckAuthenticationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthenticationInput.Unmarshal(m, b)
}
func (m *CheckAuthenticationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthenticationInput.Marshal(b, m, deterministic)
}
func (dst *CheckAuthenticationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthenticationInput.Merge(dst, src)
}
func (m *CheckAuthenticationInput) XXX_Size() int {
	return xxx_messageInfo_CheckAuthenticationInput.Size(m)
}
func (m *CheckAuthenticationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthenticationInput.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthenticationInput proto.InternalMessageInfo

func (m *CheckAuthenticationInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CheckAuthenticationInput) GetMethodArn() string {
	if m != nil {
		return m.MethodArn
	}
	return ""
}

type CheckAuthenticationByEndpointInput struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Api                  string   `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthenticationByEndpointInput) Reset()         { *m = CheckAuthenticationByEndpointInput{} }
func (m *CheckAuthenticationByEndpointInput) String() string { return proto.CompactTextString(m) }
func (*CheckAuthenticationByEndpointInput) ProtoMessage()    {}
func (*CheckAuthenticationByEndpointInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{4}
}
func (m *CheckAuthenticationByEndpointInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthenticationByEndpointInput.Unmarshal(m, b)
}
func (m *CheckAuthenticationByEndpointInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthenticationByEndpointInput.Marshal(b, m, deterministic)
}
func (dst *CheckAuthenticationByEndpointInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthenticationByEndpointInput.Merge(dst, src)
}
func (m *CheckAuthenticationByEndpointInput) XXX_Size() int {
	return xxx_messageInfo_CheckAuthenticationByEndpointInput.Size(m)
}
func (m *CheckAuthenticationByEndpointInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthenticationByEndpointInput.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthenticationByEndpointInput proto.InternalMessageInfo

func (m *CheckAuthenticationByEndpointInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CheckAuthenticationByEndpointInput) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CheckAuthenticationByEndpointInput) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CheckAuthenticationByEndpointInput) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetEventRecordsInput struct {
	Since                int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	Limit                *common.PrimitiveInt32 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetEventRecordsInput) Reset()         { *m = GetEventRecordsInput{} }
func (m *GetEventRecordsInput) String() string { return proto.CompactTextString(m) }
func (*GetEventRecordsInput) ProtoMessage()    {}
func (*GetEventRecordsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{5}
}
func (m *GetEventRecordsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRecordsInput.Unmarshal(m, b)
}
func (m *GetEventRecordsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRecordsInput.Marshal(b, m, deterministic)
}
func (dst *GetEventRecordsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRecordsInput.Merge(dst, src)
}
func (m *GetEventRecordsInput) XXX_Size() int {
	return xxx_messageInfo_GetEventRecordsInput.Size(m)
}
func (m *GetEventRecordsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRecordsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRecordsInput proto.InternalMessageInfo

func (m *GetEventRecordsInput) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetEventRecordsInput) GetLimit() *common.PrimitiveInt32 {
	if m != nil {
		return m.Limit
	}
	return nil
}

type GetEventRecordsOutput struct {
	Records              []byte   `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventRecordsOutput) Reset()         { *m = GetEventRecordsOutput{} }
func (m *GetEventRecordsOutput) String() string { return proto.CompactTextString(m) }
func (*GetEventRecordsOutput) ProtoMessage()    {}
func (*GetEventRecordsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_c00c4ec1963512c4, []int{6}
}
func (m *GetEventRecordsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRecordsOutput.Unmarshal(m, b)
}
func (m *GetEventRecordsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRecordsOutput.Marshal(b, m, deterministic)
}
func (dst *GetEventRecordsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRecordsOutput.Merge(dst, src)
}
func (m *GetEventRecordsOutput) XXX_Size() int {
	return xxx_messageInfo_GetEventRecordsOutput.Size(m)
}
func (m *GetEventRecordsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRecordsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRecordsOutput proto.InternalMessageInfo

func (m *GetEventRecordsOutput) GetRecords() []byte {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*UserClaims)(nil), "grpcapi.UserClaims")
	proto.RegisterType((*GetHierarchyRelationsInput)(nil), "grpcapi.GetHierarchyRelationsInput")
	proto.RegisterType((*GetHierarchyRelationsOutput)(nil), "grpcapi.GetHierarchyRelationsOutput")
	proto.RegisterType((*CheckAuthenticationInput)(nil), "grpcapi.CheckAuthenticationInput")
	proto.RegisterType((*CheckAuthenticationByEndpointInput)(nil), "grpcapi.CheckAuthenticationByEndpointInput")
	proto.RegisterType((*GetEventRecordsInput)(nil), "grpcapi.GetEventRecordsInput")
	proto.RegisterType((*GetEventRecordsOutput)(nil), "grpcapi.GetEventRecordsOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IAMClient is the client API for IAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IAMClient interface {
	DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error)
	CheckAuthentication(ctx context.Context, in *CheckAuthenticationInput, opts ...grpc.CallOption) (*UserClaims, error)
	CheckAuthenticationByEndpoint(ctx context.Context, in *CheckAuthenticationByEndpointInput, opts ...grpc.CallOption) (*UserClaims, error)
	GetHierarchyRelations(ctx context.Context, in *GetHierarchyRelationsInput, opts ...grpc.CallOption) (*GetHierarchyRelationsOutput, error)
	GetEventRecords(ctx context.Context, in *GetEventRecordsInput, opts ...grpc.CallOption) (*GetEventRecordsOutput, error)
}

type iAMClient struct {
	cc *grpc.ClientConn
}

func NewIAMClient(cc *grpc.ClientConn) IAMClient {
	return &iAMClient{cc}
}

func (c *iAMClient) DeepPing(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.PrimitiveString, error) {
	out := new(common.PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.IAM/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CheckAuthentication(ctx context.Context, in *CheckAuthenticationInput, opts ...grpc.CallOption) (*UserClaims, error) {
	out := new(UserClaims)
	err := c.cc.Invoke(ctx, "/grpcapi.IAM/CheckAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CheckAuthenticationByEndpoint(ctx context.Context, in *CheckAuthenticationByEndpointInput, opts ...grpc.CallOption) (*UserClaims, error) {
	out := new(UserClaims)
	err := c.cc.Invoke(ctx, "/grpcapi.IAM/CheckAuthenticationByEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetHierarchyRelations(ctx context.Context, in *GetHierarchyRelationsInput, opts ...grpc.CallOption) (*GetHierarchyRelationsOutput, error) {
	out := new(GetHierarchyRelationsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.IAM/GetHierarchyRelations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetEventRecords(ctx context.Context, in *GetEventRecordsInput, opts ...grpc.CallOption) (*GetEventRecordsOutput, error) {
	out := new(GetEventRecordsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.IAM/GetEventRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServer is the server API for IAM service.
type IAMServer interface {
	DeepPing(context.Context, *common.Void) (*common.PrimitiveString, error)
	CheckAuthentication(context.Context, *CheckAuthenticationInput) (*UserClaims, error)
	CheckAuthenticationByEndpoint(context.Context, *CheckAuthenticationByEndpointInput) (*UserClaims, error)
	GetHierarchyRelations(context.Context, *GetHierarchyRelationsInput) (*GetHierarchyRelationsOutput, error)
	GetEventRecords(context.Context, *GetEventRecordsInput) (*GetEventRecordsOutput, error)
}

func RegisterIAMServer(s *grpc.Server, srv IAMServer) {
	s.RegisterService(&_IAM_serviceDesc, srv)
}

func _IAM_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.IAM/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).DeepPing(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CheckAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthenticationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CheckAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.IAM/CheckAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CheckAuthentication(ctx, req.(*CheckAuthenticationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CheckAuthenticationByEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthenticationByEndpointInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CheckAuthenticationByEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.IAM/CheckAuthenticationByEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CheckAuthenticationByEndpoint(ctx, req.(*CheckAuthenticationByEndpointInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetHierarchyRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHierarchyRelationsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetHierarchyRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.IAM/GetHierarchyRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetHierarchyRelations(ctx, req.(*GetHierarchyRelationsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetEventRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRecordsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetEventRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.IAM/GetEventRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetEventRecords(ctx, req.(*GetEventRecordsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _IAM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.IAM",
	HandlerType: (*IAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _IAM_DeepPing_Handler,
		},
		{
			MethodName: "CheckAuthentication",
			Handler:    _IAM_CheckAuthentication_Handler,
		},
		{
			MethodName: "CheckAuthenticationByEndpoint",
			Handler:    _IAM_CheckAuthenticationByEndpoint_Handler,
		},
		{
			MethodName: "GetHierarchyRelations",
			Handler:    _IAM_GetHierarchyRelations_Handler,
		},
		{
			MethodName: "GetEventRecords",
			Handler:    _IAM_GetEventRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/grpcapi.proto",
}

func init() { proto.RegisterFile("iam/grpcapi.proto", fileDescriptor_grpcapi_c00c4ec1963512c4) }

var fileDescriptor_grpcapi_c00c4ec1963512c4 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0x25, 0xc9, 0x2f, 0xff, 0x06, 0xc4, 0x8f, 0x6e, 0x28, 0xb8, 0x6e, 0x69, 0xa9, 0xdb, 0x03,
	0x52, 0x2b, 0xa3, 0x82, 0x2a, 0xf5, 0x6a, 0x20, 0xa5, 0x56, 0x45, 0x41, 0x46, 0xed, 0xa1, 0x97,
	0x68, 0xeb, 0x1d, 0x25, 0x2b, 0xec, 0xb5, 0xb5, 0xbb, 0x46, 0xe2, 0xd6, 0xcf, 0xc3, 0x27, 0xec,
	0xb1, 0xda, 0x5d, 0xc7, 0x54, 0x40, 0x72, 0x8a, 0xdf, 0x9b, 0x37, 0xef, 0x49, 0x33, 0xb3, 0x81,
	0x27, 0x9c, 0xe6, 0xfb, 0x53, 0x59, 0xa6, 0xb4, 0xe4, 0x61, 0x29, 0x0b, 0x5d, 0x90, 0x7e, 0x0d,
	0xfd, 0x51, 0x5a, 0xe4, 0x79, 0x21, 0xf6, 0xdd, 0x8f, 0xab, 0x06, 0x7f, 0x5a, 0x00, 0xdf, 0x15,
	0xca, 0xe3, 0x8c, 0xf2, 0x5c, 0x91, 0x75, 0x68, 0x73, 0xe6, 0xb5, 0x76, 0x5b, 0x7b, 0xc3, 0xa4,
	0xcd, 0x19, 0xd9, 0x84, 0x2e, 0xe6, 0x94, 0x67, 0x5e, 0xdb, 0x52, 0x0e, 0x90, 0x3d, 0xd8, 0xc0,
	0x2a, 0xa3, 0x13, 0x3a, 0x95, 0x88, 0x6c, 0xc2, 0xa8, 0x46, 0xaf, 0x63, 0x05, 0xeb, 0x86, 0x8f,
	0x2c, 0x7d, 0x42, 0x35, 0x92, 0x1d, 0x80, 0x6b, 0x9a, 0x71, 0x36, 0x31, 0xbc, 0xf7, 0x9f, 0xd5,
	0x0c, 0x2d, 0x33, 0xae, 0x32, 0x4a, 0x7c, 0x18, 0x54, 0x0a, 0xa5, 0xa0, 0x39, 0x7a, 0x5d, 0x5b,
	0x6c, 0x30, 0x79, 0x05, 0xab, 0xe6, 0x7b, 0xa2, 0x34, 0xd5, 0x95, 0xf2, 0x7a, 0xb6, 0x0c, 0x86,
	0xba, 0xb4, 0x8c, 0xf1, 0xb6, 0x02, 0x59, 0x64, 0xa8, 0xbc, 0xbe, 0xf3, 0x36, 0x4c, 0x62, 0x88,
	0xa6, 0x9f, 0xa6, 0x29, 0x2a, 0xe5, 0x0d, 0xee, 0xfa, 0x23, 0xcb, 0x04, 0x1f, 0xc1, 0x3f, 0x45,
	0xfd, 0x85, 0xa3, 0xa4, 0x32, 0x9d, 0xdd, 0x24, 0x98, 0x51, 0xcd, 0x0b, 0xa1, 0x62, 0x51, 0x56,
	0x9a, 0x6c, 0x43, 0xdf, 0xb6, 0x37, 0xe3, 0xe8, 0x19, 0x18, 0xb3, 0xe0, 0x13, 0x3c, 0x7f, 0xb4,
	0xed, 0xbc, 0xd2, 0xa6, 0xef, 0x19, 0x0c, 0x44, 0xc1, 0x70, 0xc2, 0x99, 0xf2, 0x5a, 0xbb, 0x9d,
	0xbd, 0x61, 0xd2, 0x37, 0x38, 0x66, 0x2a, 0xf8, 0x06, 0xde, 0xf1, 0x0c, 0xd3, 0xab, 0xa8, 0xd2,
	0x33, 0x14, 0x9a, 0xa7, 0xb6, 0xd1, 0xc5, 0x6d, 0x42, 0x57, 0x17, 0x57, 0x28, 0xea, 0x30, 0x07,
	0xc8, 0x0b, 0x18, 0xe6, 0xa8, 0x67, 0x05, 0x8b, 0xa4, 0xa8, 0x57, 0x70, 0x47, 0x04, 0xbf, 0x5b,
	0x10, 0x3c, 0x62, 0x78, 0x74, 0x33, 0x16, 0xac, 0x2c, 0xb8, 0xd0, 0xcb, 0xac, 0x7d, 0x18, 0x60,
	0x2d, 0xab, 0x9d, 0x1b, 0x4c, 0xb6, 0xa0, 0xe7, 0x52, 0xea, 0xad, 0xd6, 0x88, 0x6c, 0x40, 0x87,
	0x96, 0xbc, 0x5e, 0xa3, 0xf9, 0x0c, 0x7e, 0xc2, 0xe6, 0x29, 0xea, 0xf1, 0x35, 0x0a, 0x9d, 0x60,
	0x5a, 0x48, 0xa6, 0x9a, 0x4c, 0xc5, 0x45, 0x8a, 0x36, 0xb3, 0x93, 0x38, 0x40, 0xde, 0x43, 0x37,
	0xe3, 0x39, 0x77, 0x81, 0xab, 0x07, 0x5b, 0x61, 0x7d, 0x8a, 0x17, 0xd2, 0xb0, 0xfc, 0x1a, 0x63,
	0xa1, 0x0f, 0x0f, 0x12, 0x27, 0x0a, 0x3e, 0xc0, 0xd3, 0x7b, 0xde, 0xf5, 0x88, 0x3d, 0xe8, 0x4b,
	0x47, 0x58, 0xfb, 0xb5, 0x64, 0x0e, 0x0f, 0x6e, 0x3b, 0xd0, 0x89, 0xa3, 0x33, 0x72, 0x08, 0x83,
	0x13, 0xc4, 0xf2, 0x82, 0x8b, 0x29, 0x59, 0x9b, 0xa7, 0xfc, 0x28, 0x38, 0xf3, 0xb7, 0x1f, 0x64,
	0x5e, 0x6a, 0xc9, 0xc5, 0x34, 0x58, 0x21, 0xe7, 0x30, 0x7a, 0x64, 0x9a, 0xe4, 0x75, 0x38, 0x7f,
	0x4f, 0x8b, 0x96, 0xe7, 0x8f, 0x1a, 0xc9, 0xdd, 0x53, 0x0a, 0x56, 0x48, 0x0a, 0x3b, 0x4b, 0xd7,
	0x43, 0xde, 0x2d, 0xb3, 0xbe, 0xb7, 0xc6, 0x45, 0x21, 0xcc, 0x4e, 0xe9, 0xe1, 0x39, 0x92, 0x37,
	0x8d, 0x7e, 0xf1, 0x95, 0xfb, 0x6f, 0x97, 0x8b, 0xdc, 0xc0, 0x83, 0x15, 0x92, 0xc0, 0xff, 0xf7,
	0x76, 0x41, 0x76, 0xfe, 0x6d, 0x7d, 0x70, 0x01, 0xfe, 0xcb, 0x45, 0xe5, 0xb9, 0xe7, 0xd1, 0xd6,
	0x6d, 0x7b, 0x74, 0xf9, 0xf5, 0x73, 0x38, 0x16, 0x19, 0x9f, 0xce, 0x74, 0x18, 0x5d, 0xc4, 0x61,
	0x1c, 0x9d, 0xfd, 0xea, 0xd9, 0x7f, 0xa6, 0xc3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x22,
	0x98, 0x18, 0xcc, 0x04, 0x00, 0x00,
}
