name: Release Go
on:
  release:
    types: [published]
jobs:
  build:
    name: proto-release-go
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      SERVICES: common hierarchy iam iot pas reports config authorize notification
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Go: Clean cache, install protoc compiler and fetch gRPC protoc plugin"
        run: |
          mkdir -p build/protoc
          pushd build/protoc
          wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
          unzip -o protoc*.zip
          popd
          
          go get -u google.golang.org/grpc@v1.40.0
          go get -d -u github.com/golang/protobuf/protoc-gen-go
          mkdir -p $GOPATH/src/github.com/golang

          pushd $GOPATH/src/github.com/golang
          git clone --depth 1 --branch v1.2.0 https://github.com/golang/protobuf
          popd

          go install github.com/golang/protobuf/protoc-gen-go@latest
          mv $GOPATH/bin build/bin

      - name: "Go: Generate sources"
        run: bash ${{ github.workspace }}/scripts/build_go.sh

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: "Go: Generate mod files"
        run: |
          MAJOR_VERSION=$(echo ${{ steps.get_version.outputs.VERSION }} | awk -F. '{ print $1 }')

          pushd build/go
          go mod init github.com/SKF/proto/${MAJOR_VERSION}
          find . -type f -name \*.go -exec sed -i -e "s,github.com/SKF/proto,github.com/SKF/proto/${MAJOR_VERSION},g" {} \;
          go mod tidy
          popd

      - name: "Go: Deploy generated sources back to repo"
        run: bash ${{ github.workspace }}/scripts/upload_to_github.sh go go1 build/go ${{ github.event.release.tag_name }} ${{ secrets.GITHUB_TOKEN }}
