name: Release Go
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: proto-generate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: "Go: Clean cache, install protoc compiler and fetch gRPC protoc plugin"
        run: |
          tree build
          rm -rf build

          mkdir -p build/protoc
          pushd build/protoc
          wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
          unzip -o protoc*.zip
          popd
          
          go get -u google.golang.org/grpc
          go get -d -u github.com/golang/protobuf/protoc-gen-go
          git -C $GOPATH/src/github.com/golang/protobuf checkout v1.2.0
          go install github.com/golang/protobuf/protoc-gen-go
          mv $GOPATH/bin build/bin

      - name: "Go: Generate sources"
        run: ../../scripts/build_go.sh

      - name: "Go: Deploy generated sources back to repo"
        run: bash scripts/upload_to_github.sh go go1 build/go
